# 04 — H4 protection vs possession audit (human review)

Decomposes `4.6` care and exhaustively inspects both `4.7` topics.
**Protection requires an external threat**; partner-as-danger → control, not protection.

Saved audits + packets only; rating cells stay blinded.

In [1]:
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

cwd = Path.cwd().resolve()
root = cwd
for _ in range(6):
    if (root / "configs").is_dir() and (root / "src").is_dir():
        break
    root = root.parent
sys.path.insert(0, str(root))

from src.stage11_refined_construct_analysis.analysis import notebook_helpers as nh
from src.stage11_refined_construct_analysis.analysis import review_display as rd
from src.stage11_refined_construct_analysis.analysis.constructs import normalize_code
from src.stage11_refined_construct_analysis.lookup import load_topic_lookup, topics_for_leaves

ctx = nh.setup("04_h4_protection_possession_audit")
cfg = ctx.cfg
HYP = "H4"
CODE_COL = "care_protection_code"

Project root : /home/polina/Documents/Cursor_Projects/romantic_novels_large_corpus
Config       : configs/stage11/refined_constructs.yaml
Run          : v4_l12_granular_final_call49
Outputs      : results/stage11_refined_construct_analysis/v4_l12_granular_final_call49/notebook_analysis/04_h4_protection_possession_audit

## 1. Overview — labels with codes

In [2]:
lookup = load_topic_lookup(cfg)
master = nh.load_master(cfg)
h4 = master[master[CODE_COL].notna()].copy()
h4["code_norm"] = h4[CODE_COL].map(normalize_code)
print(f"H4-coded topics: {len(h4)}")

overview = rd.annotation_overview(h4, CODE_COL)
display(overview[["topic", "taxonomy", "code", "code_norm", "mixed", "agree"]])
ctx.save_table(overview, "h4_topic_overview_labeled")
display(h4[CODE_COL].value_counts().to_frame("n"))
display(h4["code_norm"].value_counts(dropna=False).to_frame("n_norm"))

H4-coded topics: 71

                                     topic                                       taxonomy  code code_norm  mixed     agree
0   107 — Gritted Teeth and Clenched Fists          1.1 — Body Parts & Physical Reactions  H4_0      H4_0  False
1      122 — Wound Bleeding and Blood Loss    1.2 — Pain, Injury & Physical Vulnerability  H4_0      H4_0  False
2         33 — Werewolf Pack Confrontation            10.1 — Paranormal & Immortal Beings  H4_7      H4_7  False
3      69 — Visions and Nightmare Warnings            10.1 — Paranormal & Immortal Beings  H4_5      H4_5  False
4           236 — Caught Spying By The Fbi       10.3 — Mystery, Suspense & Investigation  H4_5      H4_5  False
..                                     ...                                            ...   ...       ...    ...       ...
66     73 — Quick Remarks Before Moving on  9.2 — Promise, Vow & Future-Tense Speech Acts  H4_0      H4_0  False
67             100 — Promising to Find Her  9.2 — Promise, Vow & Future-Tense Speech Acts  H4_0      H4_0  False  H1,H4,H6
68       181 — Handing Off to Someone Else  9.2 — Promise, Vow & Future-Tense Speech Acts  H4_0      H4_0  False
69        238 — Relaying A Message For Her  9.2 — Promise, Vow & Future-Tense Speech Acts  H4_4      H4_4  False
70  338 — Promising Never to Do That Again  9.2 — Promise, Vow & Future-Tense Speech Acts  H4_0      H4_0  False

[71 rows x 6 columns]

  saved table: results/stage11_refined_construct_analysis/v4_l12_granular_final_call49/notebook_analysis/04_h4_protection_possession_audit/tables/h4_topic_overview_labeled.csv  (71 rows)

                       n
care_protection_code
H4_0                  35
H4_5                   9
H4_1                   8
H4_2                   5
H4_5a                  4
H4_7                   3
H4_4                   2
H4_6                   2
H4_9                   2
H4_8                   1

           n_norm
code_norm
H4_0           35
H4_5            9
H4_1            8
H4_2            5
H4_5a           4
H4_7            3
H4_4            2
H4_6            2
H4_9            2
H4_8            1

## 2. Lexical vs contextual agreement

In [3]:
lex = nh.load_audit_jsonl(cfg, HYP, "A")
ctxu = nh.load_audit_jsonl(cfg, HYP, "B")
adj = nh.load_audit_jsonl(cfg, HYP, "C")
lex_idx = rd.audit_index(lex)
ctx_idx = rd.audit_index(ctxu)
adj_idx = rd.audit_index(adj)

agree = rd.agreement_table(h4, lex_idx, ctx_idx, adj_idx, hyp=HYP)
if not agree.empty:
    print(
        f"Lexical–contextual agreement: {agree['agree'].mean():.1%} "
        f"({int(agree['agree'].sum())}/{len(agree)})"
    )
    ctx.save_table(agree, "h4_lexical_contextual_agreement")
    disagree = agree[~agree["agree"]]
    if len(disagree):
        display(
            disagree[
                ["topic", "taxonomy", "code_a", "code_b", "code_c", "rationale_c"]
            ]
        )

Lexical–contextual agreement: 33.8% (24/71)
  saved table: results/stage11_refined_construct_analysis/v4_l12_granular_final_call49/notebook_analysis/04_h4_protection_possession_audit/tables/h4_lexical_contextual_agreement.csv  (71 rows)

                                            topic                                           taxonomy code_a      code_b code_c                                        rationale_c
2           24 — Confronting An Unwanted Marriage         4.4 — Conflict, Distance & Breakup Threats   H4_9       H4_5a  H4_5a  The consensus and dominant codes suggest a foc...
3               27 — Racing The Approaching Storm               7.3 — Risk, Danger & External Crises   H4_5       H4_5a   H4_5  The topic discusses physical protection from e...
5                33 — Werewolf Pack Confrontation                10.1 — Paranormal & Immortal Beings   H4_7        H4_5   H4_7  The topic's dominant code is H4_7, indicating ...
7          45 — Reassured Everything Will Be Fine   4.6 — Emotional Safety, Reassurance & Caretaking   H4_1        H4_4   H4_1  The topic's dominant code, H4_4 (emotional sup...
10               56 — Promising Never to Hurt You   4.6 — Emotional Safety, Reassurance & Caretaking   H4_5       H4_5a   H4_5  The topic discusses the male character physica...
11                59 — Mother's Disapproval Looms                 5.1 — Family, Kinship & Parenthood   H4_4        H4_0   H4_4  The lexical consensus of H4_4 (emotional_suppo...
12          68 — Promising to Set Things Straight      9.2 — Promise, Vow & Future-Tense Speech Acts   H4_5        H4_0   H4_5  The topic resolves around promises of physical...
13            69 — Visions and Nightmare Warnings                10.1 — Paranormal & Immortal Beings   H4_5        H4_1   H4_5  The topic revolves around external physical pr...
15            73 — Quick Remarks Before Moving on      9.2 — Promise, Vow & Future-Tense Speech Acts  H4_5a        H4_0  H4_5a  The topic's dominant code is H4_0 (off_target)...
16          78 — Swearing War Before He Takes Her      7.2 — Violence, Threats & Non-Sexual Coercion   H4_5        H4_0   H4_5  The topic discusses external physical protecti...
17         82 — Touch Her and Your Family Suffers      7.2 — Violence, Threats & Non-Sexual Coercion   H4_7  H4_0|MIXED   H4_7  The contextual dominant code H4_0 (off_target)...
18          83 — Reassured About Eating Regularly   4.6 — Emotional Safety, Reassurance & Caretaking   H4_2        H4_0   H4_2  Lexical consensus from Pass A/B is H4_2 (pract...
22            96 — Confessing Long-Standing Worry   4.6 — Emotional Safety, Reassurance & Caretaking   H4_4        H4_1   H4_1  The topic's dominant code is H4_1, indicating ...
24                 102 — Grief Etched on His Face                 3.2 — Negative Emotions & Distress   H4_1       H4_5a  H4_5a  The topic's dominant code is H4_5a, indicating...
25         107 — Gritted Teeth and Clenched Fists              1.1 — Body Parts & Physical Reactions   H4_5       H4_13   H4_5  The topic discusses physical protection from e...
28    117 — Blamed and Threatened Into Compliance      7.2 — Violence, Threats & Non-Sexual Coercion  H4_11        H4_1   H4_1  The topic's dominant code is H4_1, indicating ...
29                119 — Offering to Keep Her Safe   4.6 — Emotional Safety, Reassurance & Caretaking   H4_5       H4_5a  H4_5a  The topic discusses the character's commitment...
30            121 — Revealing Plans to The Prince  4.3 — Secrets, Misunderstandings & Hidden Info...  H4_5a        H4_6   H4_6  The topic revolves around protecting the prota...
31            122 — Wound Bleeding and Blood Loss        1.2 — Pain, Injury & Physical Vulnerability   H4_5        H4_0   H4_5  The lexical consensus and contextual dominant ...
33                  148 — Banished From The Ranch      7.2 — Violence, Threats & Non-Sexual Coercion  H4_5a       H4_13  H4_5a  The topic's dominant code is mixed (H4_13), bu...
34        157 — Swearing to Save Him From Himself            4.5 — Reconciliation, Commitments & HEA   H4_1        H4_0   H4_1  The topic discusses tender and reassuring mome...
35       161 — Reassuring Squeeze on The Shoulder   4.6 — Emotional Safety, Reassurance & Caretaking   H4_1        H4_0   H4_0  Lexical consensus from Pass A/B is H4_1 (reass...
38       175 — Gentleman Offers Steadying Support   4.6 — Emotional Safety, Reassurance & Caretaking   H4_1        H4_0   H4_0  Lexical consensus (H4_1 reassurance_tenderness...
39              181 — Handing Off to Someone Else      9.2 — Promise, Vow & Future-Tense Speech Acts   H4_7       H4_13   H4_7  The topic's dominant code is H4_13, indicating...
43   223 — Coordinating Security Against A Threat               7.3 — Risk, Danger & External Crises   H4_7        H4_0   H4_7  The lexical consensus and contextual dominant ...
45                 236 — Caught Spying By The Fbi           10.3 — Mystery, Suspense & Investigation   H4_5       H4_5a   H4_5  The dominant code H4_5a (protective commitment...
46               238 — Relaying A Message For Her      9.2 — Promise, Vow & Future-Tense Speech Acts   H4_4       H4_13   H4_4  The topic's lexical consensus of H4_4 (emotion...
47  239 — Keeping Someone Guarded and Entertained             5.2 — Friends, Allies & Social Circles  H4_5a       H4_13  H4_5a  The topic's dominant code is mixed (H4_13), bu...
48              240 — Unsure How to Offer Comfort   4.6 — Emotional Safety, Reassurance & Caretaking  H4_5a       H4_13  H4_5a  The topic's dominant code is mixed (H4_13), bu...
49          247 — Promising You Will Not Be Alone   4.6 — Emotional Safety, Reassurance & Caretaking   H4_1        H4_0   H4_1  The topic's dominant code is H4_0 (off_target)...
50          249 — Threatened With Arrest and Jail      7.2 — Violence, Threats & Non-Sexual Coercion   H4_5        H4_6   H4_6  The topic discusses the protagonist's actions ...
51                 258 — Shouting Above The Crowd              9.1 — Dialogue Delivery & Speech Tags   H4_9        H4_1   H4_1  The topic discusses reassuring and tender inte...
52           273 — Mentor Gives Firm Instructions   4.6 — Emotional Safety, Reassurance & Caretaking   H4_4        H4_0   H4_0  The lexical consensus from Pass A/B landed on ...
53           277 — Promising to Handle The Lawyer   4.6 — Emotional Safety, Reassurance & Caretaking   H4_6       H4_5a  H4_5a  The topic discusses the character's commitment...
54          282 — Struggling to Surrender Control              3.3 — Ambivalence & Internal Conflict   H4_4        H4_9   H4_9  The topic's dominant code, H4_9 (coercive cont...
58               299 — Pledging to Have Your Back   4.6 — Emotional Safety, Reassurance & Caretaking  H4_5a       H4_13  H4_5a  The topic discusses the character's commitment...
59            307 — Hauling Someone Up The Stairs   4.6 — Emotional Safety, Reassurance & Caretaking   H4_5        H4_0   H4_5  The topic discusses physical protection provid...
60                  315 — Claiming Her As His Own       4.7 — Jealousy & Possessive Romance Conflict  H4_13        H4_0   H4_8  Pass A/B yielded a lexical consensus of H4_13 ...
61           324 — Searching For A Missing Person               7.3 — Risk, Danger & External Crises  H4_5a        H4_5  H4_5a  The dominant code H4_5 (external_protection_ph...
62                    329 — Laying Down The Rules      7.2 — Violence, Threats & Non-Sexual Coercion  H4_5a        H4_0  H4_5a  The consensus code 'H4_5a' was chosen as it re...
63             335 — Killer Targets Someone Alone               7.3 — Risk, Danger & External Crises  H4_5a        H4_0  H4_5a  The topic discusses the character's commitment...
64         338 — Promising Never to Do That Again      9.2 — Promise, Vow & Future-Tense Speech Acts  H4_5a        H4_0  H4_5a  The topic revolves around promises and vows of...
65     340 — Patience Tested Through Small Trials   4.6 — Emotional Safety, Reassurance & Caretaking  H4_13        H4_0   H4_0  Pass A/B lexical consensus landed on H4_13 (mi...
66              355 — Blanket Draped Over Someone   4.6 — Emotional Safety, Reassurance & Caretaking   H4_2       MIXED   H4_2  Lexical consensus (H4_2) and the prior H3 secu...
68           358 — Reassuring Squeeze of The Hand   4.6 — Emotional Safety, Reassurance & Caretaking   H4_1       H4_5a  H4_5a  The topic's dominant code, H4_5a, represents p...
69              363 — Asking The Sheriff For Help           10.3 — Mystery, Suspense & Investigation   H4_5        H4_0   H4_5  The dominant code H4_0 (off_target) indicates ...
70                 372 — Told to Keep Up Strength   4.6 — Emotional Safety, Reassurance & Caretaking  H4_13        H4_0   H4_0  Pass A/B lexical consensus was H4_13 (mixed/un...

## 3. Exhaustive `4.7` review (only two topics)

Read both cards in full. What would falsify "protection"? Sentences where the threat is
the partner, or where the act is claiming / restricting rather than shielding from outside.

In [4]:
ids_47 = topics_for_leaves(lookup, ["4.7"])
j47 = master[master["topic_id"].isin(ids_47)].copy()
j47["code_norm"] = j47[CODE_COL].map(normalize_code)
j47_ov = rd.annotation_overview(j47, CODE_COL, extra_cols=["secondary_id"])
display(j47_ov[["topic", "taxonomy", "code", "code_norm", "secondary_id"]])
print("4.7 topics (id — label):")
for line in rd.labeled_topic_list(lookup, ids_47):
    print(f"  · {line}")
ctx.save_table(j47_ov, "h4_47_exhaustive")

                               topic                                      taxonomy  code code_norm secondary_id
0  293 — Admitting Jealousy Out Loud  4.7 — Jealousy & Possessive Romance Conflict  H4_8      H4_8          4.4
1      315 — Claiming Her As His Own  4.7 — Jealousy & Possessive Romance Conflict  H4_7      H4_7          5.2

4.7 topics (id — label):
  · 293 — Admitting Jealousy Out Loud
  · 315 — Claiming Her As His Own
  saved table: results/stage11_refined_construct_analysis/v4_l12_granular_final_call49/notebook_analysis/04_h4_protection_possession_audit/tables/h4_47_exhaustive.csv  (2 rows)

## 4. Current `4.6` code mass

Reassurance / medical / institutional care should not all count as protectiveness.

In [5]:
care = h4[h4["current_taxonomy_id"] == "4.6"]
print(f"Current 4.6 topics in H4 audit: {len(care)}")
by = (
    care.assign(
        topic=care.apply(
            lambda r: rd.fmt_topic(r["topic_id"], r["current_topic_label"]), axis=1
        )
    )
    .groupby("code_norm", dropna=False)
    .size()
    .rename("n")
    .reset_index()
    .sort_values("n", ascending=False)
)
display(by)
ctx.save_table(by, "h4_46_code_mass")

Current 4.6 topics in H4 audit: 30

  code_norm   n
0      H4_0  15
2      H4_2   5
1      H4_1   4
3      H4_5   3
4     H4_5a   3

  saved table: results/stage11_refined_construct_analysis/v4_l12_granular_final_call49/notebook_analysis/04_h4_protection_possession_audit/tables/h4_46_code_mass.csv  (5 rows)

## 5. Close reading

Force-include both `4.7` topics; otherwise disagreements / mixed / stratified sample.

In [6]:
review_ids = rd.select_review_topics(
    h4,
    hyp=HYP,
    lex_idx=lex_idx,
    ctx_idx=ctx_idx,
    adj_idx=adj_idx,
    force_ids=ids_47,
    per_code=3,
    seed=42,
)
packs = rd.show_review_set(
    cfg,
    h4,
    review_ids,
    hyp=HYP,
    lex_idx=lex_idx,
    ctx_idx=ctx_idx,
    adj_idx=adj_idx,
    code_col=CODE_COL,
    max_sentences=12,
)
ctx.save_markdown(
    rd.render_review_markdown(
        packs, title="H4 protection / possession — close-reading pack"
    ),
    "close_reading_pack",
)
ctx.save_table(
    h4[
        [
            "topic_id",
            "current_topic_label",
            "current_taxonomy_id",
            "current_taxonomy_name",
            "care_protection_code",
            "code_norm",
            "mixed_topic",
        ]
    ],
    "care_protection_topic_annotations",
)

fig, ax = plt.subplots(figsize=(8, 4))
vc = h4["code_norm"].fillna("UNMAPPED").value_counts()
ax.bar(vc.index.astype(str), vc.values)
ax.set_title("H4 normalised protection/possession codes")
plt.xticks(rotation=45, ha="right")
ctx.save_figure(fig, "h4_code_distribution")
plt.show()

Close-reading 62 of 71 topics (disagreements / mixed / manual / stratified sample).

============================================================================================
  TOPIC 293 — Admitting Jealousy Out Loud
============================================================================================
  Taxonomy : 4.7 — Jealousy & Possessive Romance Conflict
  Code     : H4_8  (norm: H4_8)
  Evidence : EXHAUSTIVE packet
  Stage08 snippets:
      · the concept of jealousy is foreign to them.
      · but this jealousy of yours is gonna ruin what you’ve got with j.d.” “i know.” “
      · we’ve been around the markets and —’ as she enthused away, i couldn’t help but feel
      · jealous.
      · should i be jealous of this cayden?”
  Novel sentences:
    · [BOOK_001, CELL_B, tertile=middle, p=0.72]
        I've always maintained that a little bit of jealousy looks good on a man. "
    · [BOOK_001, CELL_B, tertile=end, p=0.71]
        Well, of course I'm jealous," I frowned, poking him in the chest. "
    · [BOOK_001, CELL_B, tertile=end, p=0.63]
        She was also extremely irate over the fact that her boyfriend was using me to make
        her jealous—without my permission, as I've told you a couple of times.
    · [BOOK_001, CELL_B, tertile=end, p=0.62]
        I'm flattered that you're jealous, but you should know by now that no other woman
        could begin to compare with you.
    · [BOOK_001, CELL_B, tertile=end, p=0.61]
        This is not arrogance talking, this is not jealousy, it is simply a matter of
        facts."
    · [BOOK_001, CELL_B, tertile=middle, p=0.55]
        I debated staying where I was, standing firm for ethical reasons, but the thought
        that she'd be in the closed, womb-like confines of the trailer alone with Raphael
        was enough to spike my jealousy count off the chart.
    · [BOOK_001, CELL_B, tertile=begin, p=0.55]
        Not to mention you repeatedly batted your eyelashes at me in an obvious attempt to
        make him jealous.
    · [BOOK_001, CELL_B, tertile=middle, p=0.48]
        I didn't mind a little bit of a possessive attitude, but he was taking things a bit
        too far. "
    · [BOOK_001, CELL_B, tertile=begin, p=0.43]
        I bet you're one of those men who likes to feel superior to women," Roxy said
        suspiciously.
  Pass A/B/C:
    A lexical: H4_8
        All four keyword lists converge on jealous/possessive emotional experience. Main
        is dominated by 'jealous', 'jealousy', 'jealously', 'irrational', 'twinge',
        'pang' — classic internal jealousy vocabulary with no external threat actor.
        KeyBERT adds 'attracted', 'upset', 'emotional', 'concerned', 'warned', 'assured'
        — emotional arousal and interpersonal tension consistent with jealous reaction,
    B contextual: H4_8
        The overwhelming majority of sentences explicitly name or describe jealousy as
        an emotional state experienced by or attributed to characters in romantic
        contexts — classic jealous possessiveness (H4_8). Several sentences frame
        jealousy as flattering or normative ('a little bit of jealousy looks good on a
        man'; 'I'm flattered that you're jealous'), and one references 'Dark Ones' being
    C adjudicate: H4_8 action=KEEP
        Both lexical consensus and contextual dominant converge on H4_8
        (jealous_possessiveness), and the taxonomy classification (4.7 Jealousy &
        Possessive Romance Conflict) is fully consistent with this code. No external
        threat is evidenced that would warrant H4_5 or H4_6; the tension is partner-
        directed and rooted in jealousy rather than coercive restriction (H4_9) or

============================================================================================
  TOPIC 315 — Claiming Her As His Own
============================================================================================
  Taxonomy : 4.7 — Jealousy & Possessive Romance Conflict
  Code     : H4_7  (norm: H4_7)
  Evidence : EXHAUSTIVE packet
  Stage08 snippets:
      · henri, should any ask, this woman belongs to my cousin tristan—and to me.”
      · everything he was warmed in tristan’s presence, and short of sounding like one of
      · those cards that sang when opened, [person] didn’t know where to begin telling sey
      · i'll call tristan right after i get off the phone." "
      · besides, i suspect that even if i were cruel enough to hand tristan over, it would
      · gain me little except a lifetime of slavery to george.
  Novel sentences:
    · [BOOK_003, CELL_B, tertile=end, p=0.55]
        Val’s words slapped at him, forced him to realize a few things he’d rather have
        ignored.
    · [BOOK_003, CELL_B, tertile=begin, p=0.54]
        Val was your shot at actually having a real life and you let her waltz right out the
        door.”
    · [BOOK_003, CELL_B, tertile=end, p=0.53]
        Val looked at him as if he was out of his mind and that’s exactly how Dev felt. “
    · [BOOK_003, CELL_B, tertile=begin, p=0.51]
        Val wondered, just a little embarrassed to think that might be true.
    · [BOOK_003, CELL_B, tertile=begin, p=0.49]
        Devlin Hudson didn’t know it, but Val had already won the first battle for his
        heart.
    · [BOOK_003, CELL_B, tertile=end, p=0.49]
        It was as if even knowing that his parents had made up their differences, Dev was
        still determined to keep himself locked behind the walls Val had almost given up on
        smashing.
    · [BOOK_003, CELL_B, tertile=middle, p=0.47]
        His blood boiled as he looked at the computer-generated image of him and Val facing
        away from each other.
  Pass A/B/C:
    A lexical: H4_13
        Main keywords are almost entirely character names with 'comfortable' and
        'persuaded', offering no clear care/protection signal — coded off_target.
        KeyBERT, POS, and MMR share a cluster of ambiguous behavioral cues:
        'hesitation', 'nudged', 'screaming', 'behavior', 'actions', 'sentence',
        'indication', 'ends', 'ribs', 'bothered', 'grumbled', 'studying', 'sounding'.
    B contextual: H4_0
        The overwhelming majority of sentences are character-name references, dialogue
        fragments, or relational-conflict snippets with no discernible
        care/protection/control content — coded H4_0 (off-target). BOOK_003_14 ('one of
        the main reasons Dev had wanted Val to come back to him') hints at possessive
        claiming (H4_7) but is too brief to confirm coercive intent. BOOK_003_12 ('blood
    C adjudicate: H4_8 action=REINTERPRET
        Pass A/B yielded a lexical consensus of H4_13 (mixed/unclear) and a contextual
        dominant of H4_0 (off-target), but the revealed taxonomy — 4.7 Jealousy &
        Possessive Romance Conflict with a secondary of 5.2 Friends, Allies & Social
        Circles — provides decisive disambiguation. The topic's core signal is jealousy
        and possessive conflict directed at the partner within a social-circle context

============================================================================================
  TOPIC 24 — Confronting An Unwanted Marriage
============================================================================================
  Taxonomy : 4.4 — Conflict, Distance & Breakup Threats
  Code     : H4_0  (norm: H4_0)
  Stage08 snippets:
      · we’ll be married… to each other.”
      · you’re already married to me; he’ll understand.” “
      · i’ll give you a divorce and you can just walk away.
  Novel sentences:
    · [BOOK_002, CELL_D, tertile=begin, p=0.61]
        So that whole getting married and settling down part doesn't appeal to you?"
  Pass A/B/C:
    A lexical: H4_9
        The keywords 'marry', 'married', 'marriage', 'husband', 'wife', 'divorce', and
        'engaged' suggest a focus on commitment and relationships. 'Unhappy' and
        'threats' indicate potential conflict or coercion within these relationships.
        The absence of an external threat source makes 'H4_9' (coercive control) the
        most fitting code.
    B contextual: H4_5a
        The dominant code is H4_5a (protective commitment) as most sentences discuss
        marriage or commitment without an external threat. There's no external
        protection (H4_5, H4_6) or coercive control (H4_9-H4_11) mentioned. The language
        used also indicates possessive claiming (H4_7) in some sentences.
    C adjudicate: H4_5a action=REINTERPRET
        The consensus and dominant codes suggest a focus on protective commitment, not
        external protection or coercive control. The taxonomy also supports this
        interpretation.

============================================================================================
  TOPIC 27 — Racing The Approaching Storm
============================================================================================
  Taxonomy : 7.3 — Risk, Danger & External Crises
  Code     : H4_5  (norm: H4_5)
  Stage08 snippets:
      · it’ll be dark before we know it.’’
      · i don’t know if i’ll be able to get back here before the storm hits.
      · it’s going to rain and we’ll be caught out in the storm.
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=end, p=0.52]
        Their lips met, and an explosion of passion took them along on a tide, the darkness
        that surrounded them like a blanket against the rest of the world.
    · [BOOK_001, CELL_D, tertile=begin, p=0.46]
        Just as they reached the spot a man strode angrily out of a neighbouring field, and
        even in the poor light his expression could be seen as thunderous.
    · [BOOK_001, CELL_D, tertile=begin, p=0.44]
        They were still driving, the high hedges making it impossible for them to see
        anything but the road in front of them.
  Pass A/B/C:
    A lexical: H4_5
        The keywords 'rain', 'snow', 'storm', 'dark', 'dangerously' suggest external
        threats, while 'light', 'sun', 'moon' imply protection from these threats. The
        terms 'lighting', 'curtain', 'reflection' in KeyBERT, POS, and MMR also support
        this interpretation.
    B contextual: H4_5a
        Most sentences describe external conditions (rain, storm, darkness) or internal
        states (sunlight, dawn), indicating protective commitment (H4_5a) rather than
        external protection, possessive claiming, or coercive control.
    C adjudicate: H4_5 action=KEEP
        The topic discusses physical protection from external threats, which aligns with
        H4_5. No external threat is mentioned, but the topic focuses on the
        responsibility and commitment to protect, fitting H4_5a. However, since the
        taxonomy is about external crises, H4_5 is more appropriate.

============================================================================================
  TOPIC 33 — Werewolf Pack Confrontation
============================================================================================
  Taxonomy : 10.1 — Paranormal & Immortal Beings
  Code     : H4_7  (norm: H4_7)
  Stage08 snippets:
      · i’ll miss you, mr. [person].”
      · we’ll buy one on the way down to wolf hole.
      · take your woman and leave—i’ll handle the vaile wolves.”
  Novel sentences:
    · [BOOK_002, CELL_A, tertile=end, p=0.76]
        Seems odd that whoever is behind this would go after such a powerful wolf.” “
    · [BOOK_003, CELL_B, tertile=middle, p=0.60]
        It took all her will not to kick him in the face this time, like Wolf said.
    · [BOOK_003, CELL_B, tertile=middle, p=0.56]
        Wolf’s worship was practically a given for anyone wearing the cut, a source of open
        ridicule from all the members. “
  Pass A/B/C:
    A lexical: H4_7
        The keywords 'wolves', 'werewolf', 'werewolves', 'pack', 'alpha', 'creatures',
        'instincts', 'ripping', 'crouched', 'paced', 'circling', 'dangerously' suggest
        possessive claiming (H4_7) as the werewolves are protecting their territory and
        pack from external threats.
    B contextual: H4_5
        The sentences primarily discuss the presence and actions of wolves, indicating
        external protection (H4_5) or protective commitment (H4_5a) towards the
        characters. There's no possessive claiming or coercive control language.
    C adjudicate: H4_7 action=KEEP
        The topic's dominant code is H4_7, indicating possessive claiming, which aligns
        with the taxonomy of 10.1 Paranormal & Immortal Beings and the secondary theme
        of 7.3 Risk, Danger & External Crises. No external threat is evident, so H4_5a
        is not applicable. The lexical consensus also supports this code.

============================================================================================
  TOPIC 36 — Eagerly Offering to Help
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_2  (norm: H4_2)
  Stage08 snippets:
      · of course, i’ll help you.’
      · then you’ll let me help,” frances said at once, her expression eager. “
      · sure, of course, i’ll help.”
  Novel sentences:
    · [BOOK_001, CELL_B, tertile=end, p=0.80]
        And you know I’m here to help you in any way I can.”
    · [BOOK_002, CELL_D, tertile=middle, p=0.57]
        Well make yourself useful,” he said. “
    · [BOOK_001, CELL_B, tertile=end, p=0.76]
        I’ve got to do something to help.”
  Pass A/B/C:
    A lexical: H4_2
        Main keywords ('help', 'need', 'helping', 'assistance', 'helped', 'let') and
        KeyBERT keywords ('provided', 'willing', 'requested', 'promptly', 'eagerly',
        'appreciate') consistently signal practical, task-oriented assistance being
        offered or received — the hallmark of H4_2 practical_care. MMR reinforces this
        with 'promptly', 'appreciate', 'eagerly', 'pleased', 'options', and the
    B contextual: H4_2
        The overwhelming majority of sentences are simple offers or expressions of
        willingness to help ('Can I help you?', 'I'll help you.', 'Sure, I'll be glad to
        help.'). These represent practical, task-oriented assistance with no emotional
        depth, no external threat, no possessive or controlling language, and no
        romantic intensity — fitting H4_2 (practical care). One sentence ('Can I ask you
    C adjudicate: H4_2 action=RETAXONOMIZE
        All three passes converge on practical care (H4_2): lexical consensus is H4_2,
        contextual dominant is H4_2, and the prior H3 decomposition coded this topic as
        S11 (practical_help_other) with a RETAXONOMIZE action. The taxonomy placement in
        4.6 Emotional Safety, Reassurance & Caretaking is inconsistent with this
        convergence — H4_2 belongs in a practical care/help cluster rather than an
    !! manual_review_required

============================================================================================
  TOPIC 45 — Reassured Everything Will Be Fine
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_1  (norm: H4_1)
  Stage08 snippets:
      · we’ll be ok.” “
      · nadines : you’ll be ok?
      · ok, maybe a zero-tolerance one, but there’s no doubt about it, you’ll be great.
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=middle, p=0.65]
        I'm fine," Amber replied quietly. "
    · [BOOK_001, CELL_D, tertile=begin, p=0.65]
        Your wound…'" "I'm fine."
    · [BOOK_002, CELL_B, tertile=middle, p=0.78]
        Is everything okay?” “
  Pass A/B/C:
    A lexical: H4_1
        The keywords 'fine', 'ok', 'okay', 'alright', 'will', 'assured', 'smoothly'
        indicate reassurance and tenderness, suggesting a lack of external threat and
        support for the partner's autonomy.
    B contextual: H4_4
    C adjudicate: H4_1 action=KEEP
        The topic's dominant code, H4_4 (emotional support), aligns with the taxonomy's
        focus on emotional safety and reassurance. The lexical consensus code, H4_1
        (reassurance_tenderness), further supports this interpretation. No external
        threats or possessive/coercive elements are present, so H4_5a
        (protective_commitment) is not applicable.

============================================================================================
  TOPIC 56 — Promising Never to Hurt You
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_5  (norm: H4_5)
  Stage08 snippets:
      · you'll get hurt," he managed to say. "
      · you know i’ll never hurt you .”
      · i’ll make sure you aren’t hurt.” “
  Novel sentences:
    · [BOOK_001_middle, CELL_D, tertile=middle, p=0.51]
        It’s all well and good saying you avoid pain by avoiding relationships, but what
        about the wonderful things you’re avoiding as well?
    · [BOOK_001_end, CELL_D, tertile=end, p=0.57]
        He says that he knows it must hurt, but that whatever will be, will be, and that
        nothing we say or do will resolve things.
    · [BOOK_003_begin, CELL_C, tertile=begin, p=0.51]
        You didn’t hit me with a sledgehammer last night, did you?” “
    · [BOOK_003_middle, CELL_C, tertile=middle, p=0.62]
        I didn’t know why I felt hurt, but it stung not to be invited. “
  Pass A/B/C:
    A lexical: H4_5
        The keywords 'hurt', 'hurting', 'harm', 'threatened', 'causing' indicate
        external protection (H4_5) as the topic discusses protecting from a partner's
        harmful actions.
    B contextual: H4_5a
        The dominant code is H4_5a (protective commitment) as several sentences express
        a desire not to hurt someone or express remorse for doing so, without an
        external threat. There's no possessive claiming or coercive control language,
        and the threat source is unclear or internal.
    C adjudicate: H4_5 action=KEEP
        The topic discusses the male character physically protecting the female
        character from external threats, which aligns with the
        'external_protection_physical' code (H4_5).

============================================================================================
  TOPIC 59 — Mother's Disapproval Looms
============================================================================================
  Taxonomy : 5.1 — Family, Kinship & Parenthood
  Code     : H4_4  (norm: H4_4)
  Stage08 snippets:
      · does mama know you’ve left the nursery?”
      · didn’t your mom tell you i’ve been having problems?” “
      · mum will berate me for leaving graham at “this time”, and i’ll be forced to defend
      · myself, something i’m not used to doing.
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=begin, p=0.65]
        Oh, and then there's my mother... maybe we should focus on your bad habits." "
  Pass A/B/C:
    A lexical: H4_4
        The keywords 'mother', 'mom', 'mama', 'daughter', 'affection', 'taught',
        'instructed' suggest emotional support and guidance, indicating H4_4
        emotional_support.
    B contextual: H4_0
        All sentences refer to mothers or parents in a neutral or affectionate manner,
        with no indication of external protection, protective commitment, possessive
        claiming, or coercive control.
    C adjudicate: H4_4 action=RENAME
        The lexical consensus of H4_4 (emotional_support) aligns with the contextual
        dominant code H4_0 (off_target), indicating that the topic primarily revolves
        around emotional support, not physical or external protection, possessive
        claiming, or coercive control.

============================================================================================
  TOPIC 68 — Promising to Set Things Straight

============================================================================================
  TOPIC 175 — Gentleman Offers Steadying Support
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_0  (norm: H4_0)
  Stage08 snippets:
      · the occurrences of the day were too full of interest to leave elizabeth much
      · attention for any of these new friends; and she could do nothing but think, and
      · mr. [person] placed his hand on [person]’s shoulder for support as mr. [person]
      · barely walked out the front door.
      · yes, but when i fell ill, it was apparent that i could not travel all the way to
      · calais, so mr. [person] took me to the house of a friend of his: mr. [person].”
  Novel sentences:
    · [BOOK_001, CELL_B, tertile=end, p=0.51]
        On his way to see Mistress Gwyllain to explain your…ah, unexplained arrival.”
    · [BOOK_003, CELL_B, tertile=begin, p=0.51]
        Shit," grunted Sheridan, apparently immune to Owen's considerable charms. "
  Pass A/B/C:
    A lexical: H4_1
        Main keywords (mr, bingley, miss, georgiana, bennet, pemberley) anchor this
        firmly in Pride and Prejudice social/domestic circles with no external threat or
        coercive cues. KeyBERT supplies 'kindly, concerned, affection, worrying,
        longing' — all emotional warmth and tender concern. POS adds 'passionate,
        distress, warming, exciting' — emotionally charged but not threatening. MMR
    B contextual: H4_0
        The overwhelming majority of sentences are decontextualized fragments —
        character names, brief reactions, commands, and scene-setting snippets — that
        carry no discernible care/protection/control content relevant to the H4
        taxonomy. They are off-target (H4_0). Two sentences (BOOK_004_2 and BOOK_004_4)
        contain minimal practical-care signals (raising a child properly; attending to
    C adjudicate: H4_0 action=REINTERPRET
        Lexical consensus (H4_1 reassurance_tenderness) reflects surface-level emotional
        warmth present in friend-group dialogue, but the contextual dominant (H4_0
        off_target) is the decisive signal. The secondary taxonomy placement under 5.2
        Friends, Allies & Social Circles confirms that the topic's operative function is
        peer/ally dynamics rather than dyadic reassurance directed at a protagonist's

============================================================================================
  TOPIC 181 — Handing Off to Someone Else
============================================================================================
  Taxonomy : 9.2 — Promise, Vow & Future-Tense Speech Acts
  Code     : H4_0  (norm: H4_0)
  Stage08 snippets:
      · i’ll leave it to [person] to continue again now”. “
      · i’ll get [person] to approve the field trip.” “
      · and i’ll be frank.
  Novel sentences:
    · [BOOK_004, CELL_B, tertile=middle, p=0.49]
        Finally Fran had him cut off, long before he was really drunk, and when he
        complained she just told him it was a longwalk home for himondark roads, ifhe got
        obnoxious about it.
    · [BOOK_006, CELL_B, tertile=end, p=0.61]
        The thought of Frank coming to the house when I wasn’t there alarmed me.
  Pass A/B/C:
    A lexical: H4_7
        The Main and KeyBERT keywords ('wife', 'come', 'quickly') suggest possessive
        claiming, as does the MMR keyword 'stalked'. The POS keywords like 'affection'
        and 'behavior' support this, as they could indicate possessive behavior. The
        threat source is the partner, and the autonomy effect is restriction, as
        possessive claiming can limit the partner's autonomy.
    B contextual: H4_13
        Most sentences are mixed or unclear (H4_13), with a few instances of protective
        commitment (H4_5a), external protection (H4_6), possessive claiming (H4_7), and
        emotional support (H4_4). No external threats or coercive control are present.
    C adjudicate: H4_7 action=RENAME
        The topic's dominant code is H4_13, indicating mixed or unclear signals, but the
        lexical consensus is H4_7, which is possessive claiming. This suggests that
        while there are mixed signals, the possessive claiming aspect is prominent and
        should be the primary care/protection code.

============================================================================================
  TOPIC 223 — Coordinating Security Against A Threat
============================================================================================
  Taxonomy : 7.3 — Risk, Danger & External Crises
  Code     : H4_0  (norm: H4_0)
  Stage08 snippets:
      · i’ll give aidan a call, so he doesn’t send out the cavalry.”
      · there’ll be extra men on the gate,” [person] promised. “
      · but we have a gut feeling that since [person]’s been such a thorn in the side of
      · these people, if they think they’re going to get him, he’ll pull in the other
  Novel sentences:
    · [BOOK_001, CELL_A, tertile=end, p=0.59]
        Maybe if I go with Matt it will teach him not to take me for granted,” Alice said. “
    · [BOOK_001, CELL_A, tertile=middle, p=0.45]
        With time running short, the girls chalked Paddy and then left Cameron to do the
        clipping on his own while they brought Belladonna in from the field. “
    · [BOOK_001, CELL_A, tertile=begin, p=0.44]
        Lexington House had most of the Western boys and Matt Garrett, an Australian eventer
        who could be annoyingly full of himself.
  Pass A/B/C:
    A lexical: H4_7
        Keywords like 'matt', 'matty', 'mattie', 'connor', 'aidan', 'stephon' suggest
        possessive claiming. 'Partners' and 'options' imply a focus on relationships,
        while 'insisted', 'inevitable', and 'claims' indicate a strong, potentially
        possessive stance.
    B contextual: H4_0
        Most sentences are off-target (H4_0) as they do not explicitly discuss
        protection, care, or commitment. The two sentences coded as protective
        commitment (H4_5a) show Alice's intention to teach Matt a lesson, not
        necessarily to protect him. The sentence coded as possessive claiming (H4_7)
        shows Alice using Matt as a pawn in her game, not claiming him possessively.
    C adjudicate: H4_7 action=KEEP
        The lexical consensus and contextual dominant codes both point to possessive
        claiming, as the text discusses a character's desire to assert ownership over
        another. There's no evidence of an external threat, so H4_5 or H4_6 don't apply,
        and H4_5a is not appropriate as there's no safety or welfare pledge.

============================================================================================
  TOPIC 236 — Caught Spying By The Fbi
============================================================================================
  Taxonomy : 10.3 — Mystery, Suspense & Investigation
  Code     : H4_5  (norm: H4_5)
  Stage08 snippets:
      · like i’ve caught you spying.
      · he suspected he would've been released earlier in the day if not for the fbi.
      · you’ve been spying on me all that time?” “
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=begin, p=0.45]
        He was a closer, a realist, and the reason I'd created the department in the first
        place. "
    · [BOOK_002, CELL_A, tertile=middle, p=0.67]
        If the CIA has nothing on him, I just look like a crazy person out for revenge.” “
    · [BOOK_002, CELL_A, tertile=middle, p=0.60]
        Have them do a search—we’ll stay here and try to get more of a read on our
        informant.” “
    · [BOOK_003, CELL_B, tertile=end, p=0.66]
        Well, I suppose I do have some investigative skills of my own.”
  Pass A/B/C:
    A lexical: H4_5
        The keywords 'fbi', 'agent', 'investigation', 'spy', 'detective', 'spying',
        'undercover', 'agents', 'investigator', 'agency' suggest external protection,
        specifically physical, as the main theme of this topic. The other keyword lists
        ('KeyBERT', 'POS', 'MMR') also support this interpretation with words like
        'capture', 'evidence', and 'escaped', indicating a scenario where external
    B contextual: H4_5a
        Most sentences discuss investigative actions or roles, with no external or
        partner threat mentioned, fitting 'protective commitment' (H4_5a).
    C adjudicate: H4_5 action=KEEP
        The dominant code H4_5a (protective commitment) is resolved to H4_5 (external
        protection physical) as there is an external threat mentioned in the context,
        fitting the taxonomy of Mystery, Suspense & Investigation and Risk, Danger &
        External Crises.

============================================================================================
  TOPIC 238 — Relaying A Message For Her
============================================================================================
  Taxonomy : 9.2 — Promise, Vow & Future-Tense Speech Acts
  Code     : H4_4  (norm: H4_4)
  Stage08 snippets:
      · yeah, i’ll tell her,” i reply, the sudden mood change taking me by surprise. “
      · i’ll go tell her.”
      · well, maybe you’ll get another chance to tell her.”
  Novel sentences:
    · [BOOK_001, CELL_B, tertile=middle, p=0.69]
        But she won’t tell you what, specifically, it goes to show, unless you ask. “
    · [BOOK_002, CELL_D, tertile=begin, p=0.56]
        If I’d known that, I wouldn’t have done so much around here,” she teased.
    · [BOOK_002, CELL_D, tertile=middle, p=0.51]
        She said she was actually glad when the lie between her and Grandpa was over.
  Pass A/B/C:
    A lexical: H4_4
        The keywords 'tell', 'told', 'talk', 'knows', 'happened', and 'wish' suggest a
        desire for emotional support and understanding, which is reflected in the
        'emotional_support' code (H4_4). The keyword 'promises' in KeyBERT and
        'behavior' in POS and MMR suggest a commitment to maintaining a certain
        standard, which aligns with 'protective_commitment' (H4_5a). However, there are
    B contextual: H4_13
        Most sentences involve withholding or revealing information, which is unclear or
        mixed in nature. One sentence ('I should've told them you were mine from the
        beginning') indicates possessive claiming.
    C adjudicate: H4_4 action=KEEP
        The topic's lexical consensus of H4_4 (emotional_support) aligns with the
        contextual dominant of H4_13 (mixed/unclear), indicating a balance of care and
        protection themes. The taxonomy of 'Promise, Vow & Future-Tense Speech Acts'
        supports this interpretation, as the topic discusses emotional support in the
        context of future commitments.

============================================================================================
  TOPIC 239 — Keeping Someone Guarded and Entertained
============================================================================================
  Taxonomy : 5.2 — Friends, Allies & Social Circles
  Code     : H4_0  (norm: H4_0)
  Stage08 snippets:
      · i’ve always marveled at the artwork in that book, [person].
      · if trent wanted him to know the story, he would’ve told him. “
      · between the three of us, we’ll keep [person] guarded and entertained.”
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=middle, p=0.45]
        He’d renewed several advantageous acquaintances, particularly that of Lord Grey.
    · [BOOK_001, CELL_D, tertile=begin, p=0.45]
        I say, he’s an ambitious sort of fellow and he’d be looking for an earl’s daughter
        at the very least.
    · [BOOK_003, CELL_C, tertile=begin, p=0.40]
        His best friend Gareth ran the mine and took care of the men while he was away.
  Pass A/B/C:
    A lexical: H4_5a
        The keywords 'misjudged', 'denied', 'assume', 'embarrassment', 'disappointment',
        'unlikely', 'painful' suggest a situation where the characters are taking
        responsibility for their actions or feelings, without an external threat. This
        is indicative of protective commitment (H4_5a).
    B contextual: H4_13
        Most sentences are neutral or unclear, with no specific protection, care, or
        commitment mentioned. The sentence 'Austin couldn’t show up uninvited either, as
        tempting as that might be.' (BOOK_005_5) hints at protective commitment without
        an external threat, hence H4_5a.
    C adjudicate: H4_5a action=RENAME
        The topic's dominant code is mixed (H4_13), but the lexical consensus (H4_5a)
        indicates a clear protective commitment. This is supported by the taxonomy's
        secondary category of 'Emotional Safety, Reassurance & Caretaking'. Therefore,
        the topic should be renamed to reflect this protective commitment.

============================================================================================
  TOPIC 240 — Unsure How to Offer Comfort
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_0  (norm: H4_0)
  Stage08 snippets:
      · oh my god, sean!
      · sean pursed his lips, unsure he was equal to the task of comforting [person].
      · sean held out his hand and added; “now if you’ll excuse me i have a beautiful woman
      · waiting to have breakfast with me.”
  Novel sentences:
    · [BOOK_002, CELL_B, tertile=begin, p=0.50]
        Oh,” I said, thinking fast, watching as Seth started to show Liam how to use another
        nearby machine, while the Tiffanys and Brittanys gathered round, looking more
        worshipful than ever.
    · [BOOK_003, CELL_B, tertile=end, p=0.48]
        You need to stop nipping at him and face the fact that when Shon goes under, he’s
        off limits, one breath away from being a hostile at our backs.” “
  Pass A/B/C:
    A lexical: H4_5a
        The keywords 'answered', 'looked', 'said', 'mumbled', 'willing', 'shivered',
        'assume', 'anxious', 'stares', 'conscious', 'distracted' suggest a scenario
        where characters are showing protective commitment (H4_5a) towards each other,
        without any external threat.
    B contextual: H4_13
        Most sentences are unclear or off-topic (H4_13), with no specific care,
        protection, or commitment mentioned. The sentence 'You need to stop nipping at
        him and face the fact that when Shon goes under, he’s off limits, one breath
        away from being a hostile at our backs.' (BOOK_003_2) indicates coercive control
        (H4_9), but it's the only instance. The sentences mentioning names repeatedly
    C adjudicate: H4_5a action=REINTERPRET
        The topic's dominant code is mixed (H4_13), but the lexical consensus is clear
        (H4_5a). The topic primarily revolves around emotional safety and reassurance,
        with no external threat mentioned. Therefore, it's resolved to H4_5a.

============================================================================================
  TOPIC 247 — Promising You Will Not Be Alone
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_1  (norm: H4_1)
  Stage08 snippets:
      · if we make it through this alone, we’ll just be better at being alone.”
      · you’ll never be alone.
      · before you say no, i want you to know i’ll be alone mostly.
  Novel sentences:
    · [BOOK_003, CELL_B, tertile=end, p=0.67]
        If I went out alone, it seemed I felt surrounded by people who couldn’t speak to me.
    · [BOOK_003, CELL_B, tertile=begin, p=0.66]
        I promise you, you will never be alone again so long as I live.”
    · [BOOK_003, CELL_B, tertile=begin, p=0.64]
        I’ve pictured this so many times in my mind, I don’t want to wake up and find I’m
        alone again.” “
  Pass A/B/C:
    A lexical: H4_1
        The keywords 'alone', 'solitude', 'prefer', 'chose', 'insisted' suggest the
        character's preference for being alone, indicating reassurance and tenderness
        (H4_1) without any external threat or restriction of autonomy.
    B contextual: H4_0
        Most sentences express loneliness or being alone, with no external threat or
        protective commitment mentioned. A few sentences hint at wanting to be alone or
        not being alone, but they do not specify any external protection or possessive
        claiming.
    C adjudicate: H4_1 action=KEEP
        The topic's dominant code is H4_0 (off_target), but the lexical consensus is
        H4_1 (reassurance_tenderness). The topic primarily revolves around emotional
        safety and reassurance, with no evidence of external threats or
        possessive/coercive behaviors. Therefore, it is appropriate to keep the topic
        and assign it the care_protection_code H4_1.

============================================================================================
  TOPIC 249 — Threatened With Arrest and Jail
============================================================================================
  Taxonomy : 7.2 — Violence, Threats & Non-Sexual Coercion
  Code     : H4_6  (norm: H4_6)
  Stage08 snippets:
      · i'll pull you off just before we make the arrest.
      · do anything remotely similar to that again, and you’ll find yourself on your way to
      · jail.”
      · maybe they’ll come see you in prison, though i doubt it.” “
  Novel sentences:
    · [BOOK_002, CELL_A, tertile=middle, p=0.56]
        If they were caught, they would face stiff penalties, including jail time.
    · [BOOK_002, CELL_A, tertile=begin, p=0.54]
        He believes the man may have been taken prisoner or murdered by my ex-husband or a
        member of his personal security.”
  Pass A/B/C:
    A lexical: H4_5
        The keywords 'jail', 'arrested', 'prison', 'bail', 'arrest', 'crime',
        'prisoner', 'criminal', 'prisoners', 'parole' indicate external threats to the
        character's freedom and safety, thus triggering H4_5
        (external_protection_physical).
    B contextual: H4_6
        The dominant code is H4_6 (external_protection_social_legal) as many sentences
        discuss legal actions, prison, and penalties. H4_9 (coercive_control) is also
        present, indicating attempts to restrict the partner's actions. H4_1
        (reassurance_tenderness) and H4_5a (protective_commitment) are present but less
        frequent.
    C adjudicate: H4_6 action=KEEP
        The topic discusses the protagonist's actions to protect their partner from
        external social and legal threats, fitting the H4_6 code.

============================================================================================
  TOPIC 258 — Shouting Above The Crowd
============================================================================================
  Taxonomy : 9.1 — Dialogue Delivery & Speech Tags
  Code     : H4_1  (norm: H4_1)
  Stage08 snippets:
      · christine shouted after him.
      · show me she’s safe,” she shouted. “
      · she shouted in excitement the way she had before, but this time, she barely heard
      · herself, everything except for her connection to him seemed like background noise.
  Novel sentences:
    · [BOOK_001, CELL_A, tertile=begin, p=0.77]
        He wanted to pound inside her and hear her scream for more.
    · [BOOK_002, CELL_B, tertile=begin, p=0.81]
        She yelled, too, though she knew they could not hear her.
    · [BOOK_001, CELL_A, tertile=middle, p=0.81]
        He pulled back and she almost screamed.
  Pass A/B/C:
    A lexical: H4_9
        The keywords 'screamed', 'yelled', 'shouted', 'screaming', 'shrieked', 'noise',
        'heard' indicate a partner's loud and aggressive behavior, which is coercive and

============================================================================================
  TOPIC 355 — Blanket Draped Over Someone
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_2  (norm: H4_2)
  Stage08 snippets:
      · bos went over to it and draped it over dainy as a blanket.
      · still, he struggled not to groan as she got him to a sitting position, resting his
      · back against her front with the blanket draped across his lap.
      · [person] plucked at the soft down comforter draped over the bed. "
  Novel sentences:
    · [BOOK_001, CELL_B, tertile=middle, p=0.82]
        The blanket was tucked around her as if pressed carefully there by someone else.
    · [BOOK_001, CELL_B, tertile=middle, p=0.72]
        Once they had it blown up, he pulled the blanket out and spread it over the mattress
        before they sat down on it.
    · [BOOK_001, CELL_B, tertile=middle, p=0.71]
        Waiting for him to come out of the bathroom she pulled the light blanket over
        herself more to cover her bare legs than because she was cold.
    · [BOOK_001, CELL_B, tertile=middle, p=0.71]
        She sat up, groggy from sleep, the blanket falling to her waist. ‘
    · [BOOK_001, CELL_B, tertile=middle, p=0.66]
        He had laid his coat down on one side and she knew it was there for a buffer between
        her skin and the velour-covered plastic of the mattress.
    · [BOOK_001, CELL_B, tertile=middle, p=0.58]
        She snuggled down onto his coat pretending to herself that the scent of him was not
        having an impact on her emotions or physical comfort.
    · [BOOK_002, CELL_D, tertile=begin, p=0.60]
        His jacket, she realised, was still on the ground from where he had folded it to put
        under her head. ‘
    · [BOOK_003, CELL_D, tertile=middle, p=0.62]
        He shook out the comforter and sailed it over the top sheet, straightening it when
        it settled.
    · [BOOK_004, CELL_B, tertile=begin, p=0.75]
        She clutched the blanket around her shoulders closed, anxiety creeping up on her.
    · [BOOK_004, CELL_B, tertile=begin, p=0.71]
        Val shifted his attention to Cord, who knelt beside the sofa, peeling the layers of
        blanket off the prone body. “
    · [BOOK_004, CELL_B, tertile=begin, p=0.70]
        But instead of an empty seat, he saw a bundle under a blanket.
  Pass A/B/C:
    A lexical: H4_2
        All four keyword lists converge on physical tending gestures: covering,
        wrapping, tucking, draping with blankets/sheets/comforters. These are classic
        practical-care acts (H4_2) — one person physically attending to another's bodily
        comfort with no external threat present and no controlling or possessive
        dynamic. POS and MMR add 'embarrassed/terrified' but these are incidental
    B contextual: MIXED
        Topic 355 centers on blankets, bedding, and physical comfort objects. The
        majority of sentences describe practical acts of physical comfort — tucking
        blankets, spreading them, laying a coat as a cushion, carrying someone wrapped
        in blankets — which code as H4_2 (practical_care). However, a substantial
        portion of sentences are off-target (H4_0): they describe neutral physical
    C adjudicate: H4_2 action=KEEP
        Lexical consensus (H4_2) and the prior H3 security code (S5 /
        practical_care_everyday) converge on routine domestic caregiving as the dominant
        signal. The contextual dominant of MIXED is noted, but the taxonomy metadata
        (4.6 Emotional Safety, Reassurance & Caretaking; secondary 8.1 Domestic Spaces &
        Routines) grounds the topic firmly in everyday practical care acts rather than

============================================================================================
  TOPIC 356 — Admitting Exhaustion After A Long Day
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_2  (norm: H4_2)
  Stage08 snippets:
      · i am kind of tired, but you’ve done enough.
      · i’ve been riding most of the day, i’m tired.” “
      · i’ve rested more than i ever expected to rest in the whole of my lifetime during the
      · past six weeks,” he said, “and i’m feeling perfectly fresh.
  Novel sentences:
    · [BOOK_001, CELL_C, tertile=begin, p=0.70]
        I was tired and cold and done with feeling under siege for the day. “
    · [BOOK_001, CELL_C, tertile=middle, p=0.55]
        Aren’t you getting just a little tired of—” “I wasn’t kidding about the way it gets
        dark out here.
    · [BOOK_002, CELL_B, tertile=middle, p=0.69]
        You must be exhausted with all of your commitments at the moment?’ ‘
    · [BOOK_002, CELL_B, tertile=end, p=0.60]
        I was tired from a big week, my nervous energy had transformed into lethargy, and I
        was still drunkish.
  Pass A/B/C:
    A lexical: H4_2
        The keywords 'tired', 'exhausted', 'fatigue', 'drained', 'worn' indicate a state
        of physical exhaustion, which is a form of practical care (H4_2). There's no
        external threat or possessive/coercive behavior mentioned, hence 'none' for
        threat source and 'neutral' for autonomy effect.
    B contextual: H4_2
        All sentences express concern or recognition of the character's tiredness, with
        no external threat, possessive language, or coercive control present.
    C adjudicate: H4_2 action=KEEP
        The topic's dominant code is H4_2, indicating practical care, which aligns with
        the taxonomy of Emotional Safety, Reassurance & Caretaking. No external threat
        or control dynamics are evident, so H4_5a is not applicable.

============================================================================================
  TOPIC 358 — Reassuring Squeeze of The Hand
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_5a  (norm: H4_5a)
  Stage08 snippets:
      · she took bronte's hand and gave it a reassuring squeeze. "
      · ted reached for caroline's hands and smiled at her reassuring squeeze. "
      · they'll ask,” he murmured, and gave her waist a reassuring squeeze.
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=end, p=0.55]
        But my parents—" "Are fine," he interrupted, groaning when she curved her fingers as
        far as she could around his hardening shaft. "
  Pass A/B/C:
    A lexical: H4_1
        The use of words like 'reassuring', 'gently', 'calming', and 'trembling'
        indicate tenderness and emotional support (H4_1), with no external or partner
        threat present.
    B contextual: H4_5a
        The dominant code is H4_5a (protective commitment) as most sentences involve
        characters physically holding or squeezing another's hand, indicating a
        protective or reassuring gesture. There's no external threat or possessive
        language, so the threat source is 'none'.
    C adjudicate: H4_5a action=KEEP
        The topic's dominant code, H4_5a, represents protective commitment, which aligns
        with the taxonomy of Emotional Safety, Reassurance & Caretaking. There's no
        evidence of an external threat, so H4_5 or H4_6 are not applicable.

============================================================================================
  TOPIC 363 — Asking The Sheriff For Help
============================================================================================
  Taxonomy : 10.3 — Mystery, Suspense & Investigation
  Code     : H4_0  (norm: H4_0)
  Stage08 snippets:
      · sheriff, if you could give us a key and point us in the right direction, we’ll be on
      · our way.” “
      · i’ll do something—maybe i’ll run for sheriff.
      · sheriff, i appreciate your concern and i hope that means you’ll put all your
      · energies into finding this guy.
  Novel sentences:
    · [BOOK_004, CELL_A, tertile=begin, p=0.58]
        This is so much bigger than anyone knows… The sheriff glances around nervously. “
    · [BOOK_004, CELL_A, tertile=begin, p=0.55]
        Upon closer inspection, I swear both he and Sheriff McGraw look positively white. “
    · [BOOK_004, CELL_A, tertile=begin, p=0.53]
        Nearly two hours later, after I’ve nibbled on several iced oatmeal cookies and drunk
        eight glasses of sweet tea, Sheriff McGraw finally waddles in through the parlor
        doors.
  Pass A/B/C:
    A lexical: H4_5
        The use of words like 'sheriff', 'deputies', 'jail', 'weapons', and 'hailed'
        suggests a physical external threat, warranting the H4_5 code for external
        protection (physical).
    B contextual: H4_0
        The sentences primarily discuss the role and actions of a sheriff, with no
        specific protective, possessive, or coercive actions mentioned. The sentence
        'There’s a posse out hunting for you.' (BOOK_006_1) implies external protection,
        but it's the only instance.
    C adjudicate: H4_5 action=REINTERPRET
        The dominant code H4_0 (off_target) indicates that the topic does not primarily
        focus on care or protection. However, the lexical consensus of H4_5
        (external_protection_physical) suggests that there is a significant aspect of
        external protection present in the topic. Given the taxonomy of Mystery,
        Suspense & Investigation, it's likely that this protection involves safeguarding

============================================================================================
  TOPIC 372 — Told to Keep Up Strength
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_0  (norm: H4_0)
  Stage08 snippets:
      · you’ll need to keep up your strength if you’re going to wrestle with that computer.”
      · you’ll need your strength, cassia.
      · you’ll need your strength.
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=middle, p=0.50]
        No, he was not yet strong enough to embark on whatever mission this was that he’d
        assigned himself.
    · [BOOK_001, CELL_D, tertile=begin, p=0.47]
        With hard work and perseverance, I made myself the man you see before you.
    · [BOOK_001, CELL_D, tertile=begin, p=0.42]
        Whoever is on the other side of this door is uncommonly strong.
    · [BOOK_001, CELL_D, tertile=end, p=0.42]
        But that was another thing about the violently deranged: they could have the
        strength of ten men.
    · [BOOK_001, CELL_D, tertile=begin, p=0.38]
        You’re generally made of much sturdier stuff than that,” Hurst was saying. “
    · [BOOK_002, CELL_D, tertile=begin, p=0.35]
        Even in the lower ranks, the invisible masses, you needed the D i p l o m a c y | 17
        perfect background to push ahead.
  Pass A/B/C:
    A lexical: H4_13
        Main keywords (strength, stronger, weak, weakling, limitations, weaker)
        establish a comparative strength/vulnerability frame but do not clearly indicate
        whether this is self-reflection, emotional support, possessive framing, or
        coercive dynamic. KeyBERT (crushed, tied, gain) adds connotations of constraint
        and defeat that could suggest coercive control (H4_9) or emotional damage
    B contextual: H4_0
        Every sentence in this topic concerns physical or personal strength, resilience,
        and endurance as abstract qualities — either self-assessed ('I'm strong', 'I
        made myself the man you see'), observed in others ('uncommonly strong', 'strong
        and able'), or used as encouragement ('Be strong!'). None of the sentences
        involve care, protection, possessiveness, control, or relational dynamics
    C adjudicate: H4_0 action=REINTERPRET
        Pass A/B lexical consensus was H4_13 (mixed/unclear), but the contextual
        dominant is H4_0 (off_target). The prior H3 adjudication for this same topic
        reached the same conclusion via parallel logic: surface emotional language
        triggered a care/security taxonomy placement, but functional analysis determined
        the topic is not performing care or protection work in the romance-novel sense.

============================================================================================
  TOPIC 114 — Guns Aimed Across The Room
============================================================================================
  Taxonomy : 7.2 — Violence, Threats & Non-Sexual Coercion
  Code     : H4_0  (norm: H4_0)
  Stage08 snippets:
      · while [person] trussed up the englishman, caroline aimed her gun. “
      · barrette renewed his grip on the pistol, and aimed at lilly.
      · he was on his back, the chair across his legs, but his gun still aimed at [person].
      · “
  Novel sentences:
    · [BOOK_001_begin, CELL_A, tertile=begin, p=0.67]
        With a sealed hand, Eve turned back Mills's jacket, saw his weapon still holstered.
        "
    · [BOOK_001_middle, CELL_A, tertile=middle, p=0.70]
        The weapon seemed to leap in her hand as she fired it, struck the man holding the
        boy between the eyes.
    · [BOOK_001_end, CELL_A, tertile=end, p=0.67]
        She said it quickly, because she'd seen his hand tighten on his weapon. "
    · [BOOK_001_end, CELL_A, tertile=end, p=0.66]
        She said it quietly, urgently, as he lifted his weapon and placed it to the pulse at
        his throat.
    · [BOOK_002_middle, CELL_D, tertile=middle, p=0.49]
        He forced his focus from her, lifted the camera and shot off a few frames in a row.
    · [BOOK_003_begin, CELL_B, tertile=begin, p=0.66]
        Lifting the weapon, she set it on its lowest setting and carefully sited it along
        the cut, firing off one quick burst.
    · [BOOK_003_begin, CELL_B, tertile=begin, p=0.65]
        Coming upon him from behind, she placed the barrel of her weapon against the center
        of his back, directly over his heart. “
    · [BOOK_003_begin, CELL_B, tertile=begin, p=0.65]
        She clotheslined the second with an extended arm, grabbing his weapon from his
        slackened grip even as he executed a flip.
    · [BOOK_003_begin, CELL_B, tertile=begin, p=0.64]
        Lifting the weapon with an effort, she fired off several warning shots.
  Pass A/B/C:
    A lexical: H4_5
        The keywords 'gun', 'pistol', 'rifle', 'barrel', 'weapon', 'guns', 'cocked',
        'fired', 'pointed', 'aimed' indicate external physical threats, thus H4_5.
    B contextual: H4_5
        All sentences describe physical actions involving weapons, indicating external
        protection.
    C adjudicate: H4_5 action=KEEP
        The topic discusses the character's physical protection of their partner from
        external threats, aligning with the H4_5 code.

============================================================================================
  TOPIC 6 — Whispered Reassurance
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_0  (norm: H4_0)
  Stage08 snippets:
      · i’ll make sure of it,” he whispered.
      · you’ll be fine,” he whispered. “
      · quiet, subdued, she nodded and then, “you’ll be safe.”
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=end, p=0.62]
        Ian stared right back and asked slowly, clearly, enunciating every word, “Who asked
        you to?”
    · [BOOK_002, CELL_D, tertile=middle, p=0.74]
        Okay,’ she said, striving for a light tone in the heavy silence. ‘
  Pass A/B/C:
    A lexical: H4_0
        All four keyword lists are dominated by speech-act and dialogue-manner
        vocabulary (whispered, said, asked, replied, mumbled, uttered, drawled,
        tentatively, hesitation, eagerly). There is no lexical signal of care,
        protection, possessiveness, control, or emotional support. The topic describes
        conversational style and verbal exchange mechanics, placing it firmly off-target
    B contextual: H4_0
        Every sentence in this topic consists of decontextualised dialogue fragments —
        single-word responses ('Yes.', 'No.', 'Fine.'), brief speech-tag snippets ('she
        muttered.', 'she whispered.', 'she asked.'), or a philosophical aside about the
        Universe. None contain any discernible care, protection, possessiveness,
        control, or relational-dynamic content relevant to the H4 taxonomy. All are
    C adjudicate: H4_0 action=KEEP
        All three passes converge on off-target: lexical consensus H4_0, contextual
        dominant H4_0, and the prior H3 security decomposition confirmed S0 (off_target)
        for the same topic. The taxonomy label '4.6 Emotional Safety, Reassurance &
        Caretaking' reflects a category header rather than evidence of actual care or
        protection work in the topic tokens themselves. No external threat, possessive

============================================================================================
  TOPIC 173 — Waiting For Him to Wake
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_0  (norm: H4_0)
  Stage08 snippets:
      · it’s after him so you’ll just have to wait until he wakes up to get your answer.”
      · it'll put him to sleep."
      · yeah, i guess i’ll have to wait and see when he wakes up.
  Novel sentences:
    · [BOOK_001, CELL_A, tertile=end, p=0.76]
        Could he count on not waking him when he lifted him from that warm bed?
    · [BOOK_001, CELL_A, tertile=middle, p=0.69]
        He’d awakened to this darkness, and so far he hadn’t been able to work up the nerve
        to move.
    · [BOOK_001, CELL_A, tertile=end, p=0.69]
        He’d awakened to this darkness, and so far he hadn’t been able to work up the nerve
        to move.
    · [BOOK_001, CELL_A, tertile=end, p=0.69]
        He’d awakened to this darkness, and so far he hadn’t been able to work up the nerve
        to move.
    · [BOOK_002, CELL_D, tertile=middle, p=0.58]
        He looked fresh, rejuvenated, as though their little fling from last night hadn't
        permanently affected his energy.
    · [BOOK_002, CELL_D, tertile=middle, p=0.45]
        He used to jog the property's perimeter every morning, before breakfast.
    · [BOOK_003, CELL_B, tertile=middle, p=0.72]
        He's sleeping for longer periods of time at night now,” Jacob said. “
  Pass A/B/C:
    A lexical: H4_0
        All four keyword lists centre on sleep states and waking (sleep, asleep, wake,
        awoke, slept, woke, tired, sleeping, drifted), physical sensations (panting,
        pounding, warmed, temperature), and incidental scene-setting (bedside, tv, rear,
        departure, scrambled). There is no lexical signal of care, protection, threat,
        jealousy, or control. The vocabulary describes ordinary nocturnal/rest scenes
    B contextual: H4_0
        All sentences in this topic describe sleep states, fatigue, wakefulness, and
        monitoring of whether a person is asleep. There is no care, protection,
        possessiveness, control, or relational dynamic expressed — the content is purely
        observational or descriptive of physical sleep/rest states. None of the
        sentences contain romance-relevant care-protection content, making H4_0
    C adjudicate: H4_0 action=KEEP
        All three passes converge on off-target (H4_0). Lexical consensus, contextual
        dominant, and the prior H3 S0 ruling all agree that this topic performs a
        temporal/structural narrative function rather than any care or protection
        function. The taxonomy primary label 'Emotional Safety, Reassurance &
        Caretaking' is a surface-level mismatch: the topic content is about time and

============================================================================================
  TOPIC 46 — Asking Someone to Trust You
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_1  (norm: H4_1)
  Stage08 snippets:
      · you’ll just have to trust me.”
      · he’ll trust you if you promise to keep me in sight.” “
      · my trust that he’ll bring me to safety.
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=begin, p=0.27]
        The critics wanted to prove that setting goals, drawing graphs, measuring results
        and evaluating the performance of individuals was nothing less than taking the place
        of trusting the Holy Spirit to give increase.
    · [BOOK_002, CELL_D, tertile=begin, p=0.61]
        Trust us, all we need to do to you can be done here,” one of the other guys said.
  Pass A/B/C:
    A lexical: H4_1
        The keywords 'trust', 'trusted', 'betrayed', 'betray', 'trusting', and 'you'
        indicate a focus on trust and its breach, suggesting reassurance and tenderness
        (H4_1). There are no external threats or possessive/coercive elements mentioned.
    B contextual: H4_1
        The sentences primarily discuss trust, with no external threats or possessive
        claiming language.
    C adjudicate: H4_1 action=KEEP
        The topic's dominant and consensus codes both indicate H4_1, which aligns with
        the taxonomy of Emotional Safety, Reassurance & Caretaking. The topic focuses on
        providing emotional comfort and reassurance, with no evidence of external
        threats or coercive control.

============================================================================================
  TOPIC 190 — Offering to Get Someone Cleaned Up
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : H4_2  (norm: H4_2)
  Stage08 snippets:
      · i’ll get cleaned up here as soon as i can.
      · i’ll pay to have it cleaned.” “
      · i'll get her cleaned up," said a handsome groom, taking her arm. "
  Novel sentences:
    · [BOOK_001, CELL_C, tertile=middle, p=0.55]
        I will clean up the battlefield while you drink plenty of fluids.
    · [BOOK_001, CELL_C, tertile=middle, p=0.49]
        I know you would prefer to burn it yourselves out of respect, but my way will be
        faster, cleaner and will ensure no parasites escape.
    · [BOOK_002, CELL_D, tertile=middle, p=0.54]
        May I know why you gave Mr. Thesiger the brush off just now?”
    · [BOOK_002, CELL_D, tertile=middle, p=0.45]
        Don’t you see that if you go ahead with this annulment, if you air the Roxtons’
        dirty laundry in public, I will be utterly, utterly ruined.
    · [BOOK_002, CELL_D, tertile=begin, p=0.41]
        A lackey came out from behind the butler with pan and brush and quickly set to
        sweeping up the shards of broken glass from Deb’s smashed wine glass.
  Pass A/B/C:
    A lexical: H4_2
        The keywords 'clean', 'cleaning', 'cleaned', 'mess', 'freshen', 'wipe',
        'sweeping', 'dump', 'provide', 'assured', 'planned' indicate practical care
        (H4_2) without any external threat or possessive/coercive behavior.
    B contextual: H4_2
    C adjudicate: H4_2 action=KEEP
        The topic's dominant code is H4_2, indicating practical care, which aligns with
        the taxonomy of Emotional Safety, Reassurance & Caretaking. No external threat
        or control dynamics are evident, so H4_5a is not applicable.

============================================================================================
  TOPIC 91 — Arguing Over Guns and Weapons
============================================================================================
  Taxonomy : 7.1 — Interpersonal Non-Romantic Conflict
  Code     : H4_5  (norm: H4_5)
  Stage08 snippets:
      · i’ll be better armed as well.
      · i don’t like guns, they’re only for bad things, and all they do are hurt people, so
      · i’ll thank you to get them away from me, now."
      · maybe i’ll get a shot with him next.
  Novel sentences:
    · [BOOK_001, CELL_A, tertile=end, p=0.62]
        Tell them someone was cleaning a gun, and it went off accidentally,” Sebastian said.
        “
    · [BOOK_001, CELL_A, tertile=end, p=0.59]
        The boy came here the night of the shooting, ranting about having killed you.
    · [BOOK_003, CELL_B, tertile=end, p=0.64]
        I called his name and that's when I saw the gun on the ground.
    · [BOOK_003, CELL_B, tertile=end, p=0.48]
        Yeah, X had his team come after me because he was afraid someone else would get gun
        happy.
  Pass A/B/C:
    A lexical: H4_5
        The keywords 'gun', 'shot', 'shoot', 'guns', 'shots', 'bullet', 'shooting',
        'bullets', 'weapon', 'pistol' along with 'weapons', 'fired', 'aimed',
        'practice', 'squeeze', 'intend' suggest external physical protection or threat.
    B contextual: H4_5
        The dominant code is H4_5 (external protection physical) as many sentences
        discuss protecting from external threats like shooters. H4_5a (protective
        commitment) is also present, showing responsibility without an external threat.
        H4_9 (coercive control) appears in a few sentences, indicating a partner as a
        danger. There's no possessive claiming or jealous possessiveness, and no mixed
    C adjudicate: H4_5 action=KEEP
        The topic discusses external physical protection, with evidence of an external
        threat, such as 'He shielded her from the incoming bullet'.

============================================================================================
  TOPIC 51 — Locked Up By A Vampire
============================================================================================
  Taxonomy : 7.2 — Violence, Threats & Non-Sexual Coercion
  Code     : H4_5  (norm: H4_5)
  Stage08 snippets:
      · you’ve kept me locked up—” “in the best room money can buy…” “i haven’t seen the
      · outside world in two weeks—” “you’re a vampire,” he said, frowning a bit. “
      · they can turn me back into a vampire, and i’d binge until i’ve made up for every day
      · i haven’t fed.
      · and you’ve never even considered being with a vampire?
  Novel sentences:
    · [BOOK_001, CELL_B, tertile=end, p=0.64]
        Of course there was a vampire story mixed in there and I love some vampire action.
    · [BOOK_001, CELL_B, tertile=end, p=0.57]
        There is one short m/f scene where a woman is being sucked dry by a vampire during
        sex but its no big deal.
    · [BOOK_001, CELL_B, tertile=end, p=0.36]
        Top2Bottom Reviews Reviews for THIRST say: Lisa Worrall has crafted a smart and
        interesting story of soul deep connection and love against a backdrop of vampires,
        retribution and loss.
    · [BOOK_004, CELL_A, tertile=middle, p=0.78]
        The vampire didn’t want to be a murderer, as I once suspected.
  Pass A/B/C:
    A lexical: H4_5
        The keywords 'vampire', 'vampires', 'vamp', 'vamps', 'vampyre', 'blood',
        'wraith', 'wraiths', 'creatures', 'feeding', 'threats' suggest external physical
        threats from vampires to humans, triggering H4_5 (external protection -
        physical).
    B contextual: H4_5
        The dominant code is H4_5 (external protection physical) as many sentences
        mention vampires, which are external threats. There's no possessive claiming or
        coercive control language used.
    C adjudicate: H4_5 action=KEEP
        The topic discusses the hero physically protecting the heroine from an external
        threat, fitting the H4_5 code.

============================================================================================
  TOPIC 184 — Racing to Stop A Spreading Fire
============================================================================================
  Taxonomy : 7.3 — Risk, Danger & External Crises
  Code     : H4_5  (norm: H4_5)
  Stage08 snippets:
      · you’ve got the fire.
      · it looks like we’ve got an arson and a murder on our hands.” “
      · we’ve got to get down to the fire station and get rolling before that fire starts to
      · spread.”
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=middle, p=0.56]
        He’d already called and checked in, and there were no raging fires that needed to be
        put out, but he still wanted to get there quickly.
    · [BOOK_002, CELL_C, tertile=middle, p=0.55]
        Her body was on fire, and Ransom had the equipment to put it out.
    · [BOOK_002, CELL_C, tertile=begin, p=0.51]
        You’re still making sure the gas line to the stove is off when you leave, right?” “
    · [BOOK_002, CELL_C, tertile=end, p=0.44]
        This news trumped everything else on folks’ minds: what people got for Christmas,
        holiday vacation stories, the one-hundred-year-old Methodist church destroyed by
        arson fire, and even the first snowfall Sienna had seen in fifty years.
    · [BOOK_004, CELL_C, tertile=begin, p=0.54]
        The redhead had the power to take the incident from the frying pan to the fire.
  Pass A/B/C:
    A lexical: H4_5
        The keywords and phrases in all lists (Main, KeyBERT, POS, MMR) revolve around
        fire and its effects, indicating a threat (external in this case, as it's not a
        partner). However, there's no indication of any protective action or commitment,
        making it 'neutral' in terms of autonomy effect.
    B contextual: H4_5
        The dominant code is H4_5 (external protection, physical) as many sentences
        refer to fire, which is an external threat. There's also some practical care
        (H4_2) and protective commitment (H4_5a) present, but not as prevalent.
    C adjudicate: H4_5 action=KEEP
        The topic discusses physical protection from external threats, aligning with the
        lexical and contextual dominant codes.

============================================================================================
  TOPIC 294 — Accepting Whatever Punishment Is Deserved
============================================================================================
  Taxonomy : 7.2 — Violence, Threats & Non-Sexual Coercion
  Code     : H4_9  (norm: H4_9)
  Stage08 snippets:
      · then i guess i’ll just have to accept your punishment.” “
      · you’ll be punished.” “
      · i’ll take whatever punishment i deserve, but i won’t give him up.” “
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=begin, p=0.50]
        I’ll need somebody to heel the ladder if I come down with a victim.”
    · [BOOK_002, CELL_B, tertile=middle, p=0.44]
        If I had known that I was going to be treated in this fashion…” “What would you have
        done?”
    · [BOOK_003, CELL_C, tertile=middle, p=0.41]
        Did the light spankings he gave while they were in the throws of passion count as
        browbeating?
    · [BOOK_004, CELL_B, tertile=begin, p=0.67]
        That I am happy to say shall be a fitting punishment for you both.” “
    · [BOOK_004, CELL_B, tertile=end, p=0.54]
        All this coming from the man who had decapitated my mother and tried to rape me.
  Pass A/B/C:
    A lexical: H4_9
        The keywords 'punish', 'punished', 'raped', 'rape', 'rapist', 'violently',
        'warned', 'refused' and 'deserve' indicate coercive control by a partner,
        restricting the autonomy of the other person.
    B contextual: H4_9
        The dominant code is H4_9 (coercive control) as the sentences repeatedly mention
        punishment, which suggests a pattern of controlling behavior from a partner.
    C adjudicate: H4_9 action=RENAME
        The topic's dominant code is H4_9, indicating coercive control, which aligns
        with the taxonomy of Violence, Threats & Non-Sexual Coercion. No external threat
        is mentioned, so H4_5a is not applicable. The topic does not fit other
        care/control codes, so renaming is appropriate.

  saved markdown: results/stage11_refined_construct_analysis/v4_l12_granular_final_call49/notebook_analysis/04_h4_protection_possession_audit/tables/close_reading_pack.md
  saved table: results/stage11_refined_construct_analysis/v4_l12_granular_final_call49/notebook_analysis/04_h4_protection_possession_audit/tables/care_protection_topic_annotations.csv  (71 rows)

  saved figure: results/stage11_refined_construct_analysis/v4_l12_granular_final_call49/notebook_analysis/04_h4_protection_possession_audit/figures/h4_code_distribution.png

/tmp/ipykernel_99523/3490380194.py:49: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

Primary refined contrast later: external_protection / (possessive_claiming +
coercive_control). If either side stays extremely sparse → H4 underpowered.

print("H4 audit review complete.")