# 06 — H6 arc semantics audit (human review)

Main-couple vs non-couple conflict, and topic × position weights \(W_{tkr}\).
High `4.4` label fidelity ≠ “is it **main-couple** conflict?”

Saved audits + packets only. Rating cells stay blinded; sentence tertiles are visible
because H6 is position-aware.

In [1]:
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

cwd = Path.cwd().resolve()
root = cwd
for _ in range(6):
    if (root / "configs").is_dir() and (root / "src").is_dir():
        break
    root = root.parent
sys.path.insert(0, str(root))

from src.stage11_refined_construct_analysis.analysis import notebook_helpers as nh
from src.stage11_refined_construct_analysis.analysis import review_display as rd
from src.stage11_refined_construct_analysis.analysis.constructs import normalize_code

ctx = nh.setup("06_h6_arc_semantics_audit")
cfg = ctx.cfg
HYP = "H6"
CODE_COL = "arc_role"

Project root : /home/polina/Documents/Cursor_Projects/romantic_novels_large_corpus
Config       : configs/stage11/refined_constructs.yaml
Run          : v4_l12_granular_final_call49
Outputs      : results/stage11_refined_construct_analysis/v4_l12_granular_final_call49/notebook_analysis/06_h6_arc_semantics_audit

## 1. Overview — arc roles with topic labels

In [2]:
master = nh.load_master(cfg)
h6 = master[master[CODE_COL].notna()].copy()
h6["code_norm"] = h6[CODE_COL].map(normalize_code)
print(f"H6-coded topics: {len(h6)}")

overview = rd.annotation_overview(
    h6,
    CODE_COL,
    extra_cols=["main_couple_prob", "non_couple_prob", "unclear_prob"],
)
display(
    overview[
        [
            "topic",
            "taxonomy",
            "code",
            "code_norm",
            "main_couple_prob",
            "non_couple_prob",
        ]
    ]
)
ctx.save_table(overview, "h6_topic_overview_labeled")
display(h6[CODE_COL].value_counts().head(25).to_frame("n"))
display(h6["code_norm"].value_counts(dropna=False).to_frame("n_norm"))

H6-coded topics: 54

                                              topic                                           taxonomy    code code_norm  main_couple_prob  non_couple_prob
0                   124 — Scooped Up in A Tight Hug             2.2 — Kissing & Non-Explicit Affection   ARC_7     ARC_7            0.8500           0.1000
1               126 — Fingertips Stroking Her Cheek             2.2 — Kissing & Non-Explicit Affection   ARC_7     ARC_7            0.8500           0.1000
2                    102 — Grief Etched on His Face                 3.2 — Negative Emotions & Distress  ARC_10    ARC_10            0.8500           0.1000
3                  285 — Confessing Years of Hatred                 3.2 — Negative Emotions & Distress   ARC_2     ARC_2            0.8500           0.1000
4                        38 — Admitting Shared Pain  4.2 — Ongoing Courtship & Everyday Relational ...  ARC_10    ARC_10            0.8500           0.1000
5           232 — Conversation Cut Short By Arrival  4.2 — Ongoing Courtship & Everyday Relational ...  ARC_10    ARC_10            0.8500           0.1000
6                 37 — Defending A Close Friendship  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_1     ARC_1            0.8500           0.1000
7                              94 — Caught in A Lie  4.3 — Secrets, Misunderstandings & Hidden Info...   MIXED      None            0.8500           0.1000
8              109 — Seeing Past A Guarded Identity  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_5     ARC_5            0.8500           0.1000
9               121 — Revealing Plans to The Prince  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_0     ARC_0            0.1000           0.8000
10                    130 — Revealing A Secret Plan  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_0     ARC_0            0.1000           0.8000
11              177 — Seeing Past A Hidden Identity  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_1     ARC_1            0.8500           0.1000
12                 194 — Promising to Keep A Secret  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_5     ARC_5            0.8500           0.1000
13            214 — Demanding to Know What Happened  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_1     ARC_1            0.8500           0.1000
14           237 — Hiding Someone Before He Arrives  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_5     ARC_5            0.8500           0.1000
15                    248 — Arranging A Cover Story  4.3 — Secrets, Misunderstandings & Hidden Info...  ARC_10    ARC_10            0.1000           0.8000
16                264 — Accused of Hiding Something  4.3 — Secrets, Misunderstandings & Hidden Info...   MIXED      None            0.8500           0.1000
17  265 — Mismatched Expectations About Seriousness  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_4     ARC_4            0.8500           0.1000
18                 272 — Silence Held Until Arrival  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_1     ARC_1            0.8500           0.1000
19               286 — Trying to Regain Good Graces  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_0     ARC_0            0.1000           0.8000
20     301 — Confessing A Thin Relationship History  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_1     ARC_1            0.8500           0.1000
21             303 — Confessing Long-Hidden Secrets  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_1     ARC_1            0.8500           0.1000
22                 314 — Fiancé Becoming A Stranger  4.3 — Secrets, Misunderstandings & Hidden Info...  ARC_10    ARC_10            0.8500           0.1000
23                319 — Confessing A Costly Mistake  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_1     ARC_1            0.8500           0.1000
24           346 — Delivering Urgent News in Secret  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_0     ARC_0            0.1000           0.8000
25          362 — Keeping Someone Watched and Close  4.3 — Secrets, Misunderstandings & Hidden Info...  ARC_10    ARC_10            0.8500           0.1000
26                     3 — Demanding An Explanation         4.4 — Conflict, Distance & Breakup Threats   ARC_5     ARC_5            0.8500           0.1000
27            24 — Confronting An Unwanted Marriage         4.4 — Conflict, Distance & Breakup Threats   MIXED      None            0.8500           0.1000
28                    43 — Pissed Off and Grumbling         4.4 — Conflict, Distance & Breakup Threats   MIXED      None            0.8500           0.1000
29            85 — Offering and Refusing An Apology         4.4 — Conflict, Distance & Breakup Threats   ARC_6     ARC_6            0.8500           0.1000
30                      129 — Accused of Not Caring         4.4 — Conflict, Distance & Breakup Threats   ARC_4     ARC_4            0.8500           0.1000
31       210 — Expelled For Pursuing A Relationship         4.4 — Conflict, Distance & Breakup Threats   MIXED      None            0.8500           0.1000
32                     256 — Refusing to Let It End         4.4 — Conflict, Distance & Breakup Threats   ARC_0     ARC_0            0.1000           0.8000
33            316 — Snapping Over Money and Control         4.4 — Conflict, Distance & Breakup Threats   ARC_0     ARC_0            0.1000           0.8000
34                   29 — Confessing Long-Held Love            4.5 — Reconciliation, Commitments & HEA   ARC_8     ARC_8            0.8500           0.1000
35          128 — Confessing How Much You've Missed            4.5 — Reconciliation, Commitments & HEA   ARC_7     ARC_7            0.8500           0.1000
36          157 — Swearing to Save Him From Himself            4.5 — Reconciliation, Commitments & HEA   ARC_7     ARC_7            0.8500           0.1000
37         242 — Trading Forgiveness For Old Wrongs            4.5 — Reconciliation, Commitments & HEA   ARC_6     ARC_6            0.8500           0.1000
38               305 — Confessing A Lifelong Regret            4.5 — Reconciliation, Commitments & HEA   ARC_7     ARC_7            0.8500           0.1000
39                        6 — Whispered Reassurance   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_0     ARC_0            0.1000           0.8000
40                    36 — Eagerly Offering to Help   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_0     ARC_0            0.1000           0.8000
41           45 — Reassured Everything Will Be Fine   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_7     ARC_7            0.8500           0.1000
42                 46 — Asking Someone to Trust You   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_7     ARC_7            0.8500           0.1000
43                 56 — Promising Never to Hurt You   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_6     ARC_6            0.8500           0.1000
44              96 — Confessing Long-Standing Worry   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_4     ARC_4            0.8500           0.1000
45                  119 — Offering to Keep Her Safe   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_9     ARC_9            0.8500           0.1000
46         175 — Gentleman Offers Steadying Support   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_7     ARC_7            0.8500           0.1000
47                240 — Unsure How to Offer Comfort   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_7     ARC_7            0.8500           0.1000
48            247 — Promising You Will Not Be Alone   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_7     ARC_7            0.8500           0.1000
49                293 — Admitting Jealousy Out Loud       4.7 — Jealousy & Possessive Romance Conflict   ARC_4     ARC_4            0.8500           0.1000
50               167 — Planning A Wedding Reception  5.3a — Romantic Social Rituals & Public Couple...   ARC_8     ARC_8            0.8500           0.1000
51            78 — Swearing War Before He Takes Her      7.2 — Violence, Threats & Non-Sexual Coercion   ARC_9     ARC_9            0.8500           0.1000
52                      100 — Promising to Find Her      9.2 — Promise, Vow & Future-Tense Speech Acts  ARC_10    ARC_10            0.8500           0.1000
53           338 — Promising Never to Do That Again      9.2 — Promise, Vow & Future-Tense Speech Acts   ARC_0     ARC_0            0.1000           0.8000

  saved table: results/stage11_refined_construct_analysis/v4_l12_granular_final_call49/notebook_analysis/06_h6_arc_semantics_audit/tables/h6_topic_overview_labeled.csv  (54 rows)

           n
arc_role
ARC_7     10
ARC_0      9
ARC_1      7
ARC_10     7
MIXED      5
ARC_5      4
ARC_4      4
ARC_6      3
ARC_8      2
ARC_9      2
ARC_2      1

           n_norm
code_norm
ARC_7          10
ARC_0           9
ARC_1           7
ARC_10          7
None            5
ARC_5           4
ARC_4           4
ARC_6           3
ARC_8           2
ARC_9           2
ARC_2           1

## 2. Lexical vs contextual agreement

In [3]:
lex = nh.load_audit_jsonl(cfg, HYP, "A")
ctxu = nh.load_audit_jsonl(cfg, HYP, "B")
adj = nh.load_audit_jsonl(cfg, HYP, "C")
lex_idx = rd.audit_index(lex)
ctx_idx = rd.audit_index(ctxu)
adj_idx = rd.audit_index(adj)

agree = rd.agreement_table(h6, lex_idx, ctx_idx, adj_idx, hyp=HYP)
if not agree.empty:
    print(
        f"Lexical–contextual agreement: {agree['agree'].mean():.1%} "
        f"({int(agree['agree'].sum())}/{len(agree)})"
    )
    ctx.save_table(agree, "h6_lexical_contextual_agreement")
    disagree = agree[~agree["agree"]]
    if len(disagree):
        display(
            disagree[
                ["topic", "taxonomy", "code_a", "code_b", "code_c", "rationale_c"]
            ]
        )

Lexical–contextual agreement: 35.2% (19/54)

  saved table: results/stage11_refined_construct_analysis/v4_l12_granular_final_call49/notebook_analysis/06_h6_arc_semantics_audit/tables/h6_lexical_contextual_agreement.csv  (54 rows)

                                              topic                                           taxonomy  code_a  code_b  code_c                                        rationale_c
1                         6 — Whispered Reassurance   4.6 — Emotional Safety, Reassurance & Caretaking  ARC_10   ARC_0   ARC_0  The contextual dominant judgment (ARC_0) holds...
3                    29 — Confessing Long-Held Love            4.5 — Reconciliation, Commitments & HEA   MIXED  ARC_10   ARC_8  The lexical consensus (MIXED) and contextual d...
5                 37 — Defending A Close Friendship  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_0   ARC_1   ARC_1  Lexical consensus (ARC_0 / off_target) was ove...
6                        38 — Admitting Shared Pain  4.2 — Ongoing Courtship & Everyday Relational ...   MIXED  ARC_10  ARC_10  The lexical consensus (MIXED) and contextual d...
7                     43 — Pissed Off and Grumbling         4.4 — Conflict, Distance & Breakup Threats   ARC_2   ARC_4   MIXED  Lexical consensus (ARC_2) and contextual domin...
8            45 — Reassured Everything Will Be Fine   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_7  ARC_10   ARC_7  The lexical consensus (ARC_7) and the taxonomy...
9                  46 — Asking Someone to Trust You   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_1   ARC_7   ARC_7  The taxonomy (4.6 Emotional Safety, Reassuranc...
10                 56 — Promising Never to Hurt You   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_4   ARC_6   ARC_6  The lexical consensus (ARC_4) reflects surface...
13                             94 — Caught in A Lie  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_5   ARC_1   MIXED  Lexical consensus (ARC_5 disclosure) and conte...
14              96 — Confessing Long-Standing Worry   4.6 — Emotional Safety, Reassurance & Caretaking  ARC_10   ARC_4   ARC_4  The lexical consensus (ARC_10) reflects surfac...
17             109 — Seeing Past A Guarded Identity  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_5  ARC_10   ARC_5  Lexical consensus (ARC_5 disclosure) and taxon...
19              121 — Revealing Plans to The Prince  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_9   ARC_0   ARC_0  Adjudication resolves the conflict between lex...
20                  124 — Scooped Up in A Tight Hug             2.2 — Kissing & Non-Explicit Affection   ARC_7  ARC_10   ARC_7  The contextual dominant flagged ARC_10 (ambigu...
22          128 — Confessing How Much You've Missed            4.5 — Reconciliation, Commitments & HEA   ARC_7   ARC_3   ARC_7  The contextual dominant code ARC_3 (separation...
23                      129 — Accused of Not Caring         4.4 — Conflict, Distance & Breakup Threats   ARC_4  ARC_10   ARC_4  Lexical consensus (ARC_4: relationship_caused_...
24                    130 — Revealing A Secret Plan  4.3 — Secrets, Misunderstandings & Hidden Info...  ARC_10   ARC_0   ARC_0  Adjudication resolves the Pass A/B tension as ...
25          157 — Swearing to Save Him From Himself            4.5 — Reconciliation, Commitments & HEA   MIXED   ARC_0   ARC_7  The lexical consensus (MIXED) and contextual d...
27         175 — Gentleman Offers Steadying Support   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_4  ARC_10   ARC_7  The lexical consensus (ARC_4) flags relationsh...
28              177 — Seeing Past A Hidden Identity  4.3 — Secrets, Misunderstandings & Hidden Info...  ARC_10   ARC_2   ARC_1  Lexical consensus was ARC_10 (unclear) and con...
30       210 — Expelled For Pursuing A Relationship         4.4 — Conflict, Distance & Breakup Threats   ARC_6   MIXED   MIXED  Lexical consensus (ARC_6 repair) and contextua...
31            214 — Demanding to Know What Happened  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_2  ARC_10   ARC_1  Lexical consensus (ARC_2 escalation_conflict) ...
33           237 — Hiding Someone Before He Arrives  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_4  ARC_10   ARC_5  Lexical consensus (ARC_4: relationship_caused_...
34                240 — Unsure How to Offer Comfort   4.6 — Emotional Safety, Reassurance & Caretaking  ARC_10   ARC_0   ARC_7  The lexical consensus (ARC_10) and contextual ...
36            247 — Promising You Will Not Be Alone   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_3   ARC_4   ARC_7  The lexical consensus (ARC_3) and contextual d...
38                     256 — Refusing to Let It End         4.4 — Conflict, Distance & Breakup Threats   ARC_4   ARC_0   ARC_0  Lexical consensus (ARC_4) reflects surface con...
39                264 — Accused of Hiding Something  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_5   ARC_9   MIXED  Lexical consensus (ARC_5 disclosure) and conte...
40  265 — Mismatched Expectations About Seriousness  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_4   ARC_0   ARC_4  Adjudication resolves the lexical–contextual s...
41                 272 — Silence Held Until Arrival  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_1  ARC_10   ARC_1  Lexical consensus (ARC_1 misunderstanding) and...
42                 285 — Confessing Years of Hatred                 3.2 — Negative Emotions & Distress   ARC_5   ARC_2   ARC_2  Lexical consensus flagged ARC_5 (disclosure), ...
45     301 — Confessing A Thin Relationship History  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_4   ARC_1   ARC_1  Lexical consensus landed on ARC_4 (relationshi...
46             303 — Confessing Long-Hidden Secrets  4.3 — Secrets, Misunderstandings & Hidden Info...  ARC_10   ARC_0   ARC_1  Adjudication resolves the tension between lexi...
47               305 — Confessing A Lifelong Regret            4.5 — Reconciliation, Commitments & HEA   ARC_4  ARC_10   ARC_7  The lexical consensus (ARC_4) and contextual d...
49            316 — Snapping Over Money and Control         4.4 — Conflict, Distance & Breakup Threats   ARC_4   ARC_0   ARC_0  Lexical consensus (ARC_4) reflects surface con...
51           338 — Promising Never to Do That Again      9.2 — Promise, Vow & Future-Tense Speech Acts  ARC_10   ARC_0   ARC_0  Contextual dominant (ARC_0) is the stronger si...
52           346 — Delivering Urgent News in Secret  4.3 — Secrets, Misunderstandings & Hidden Info...   MIXED   ARC_0   ARC_0  Lexical consensus was MIXED, but contextual do...

## 3. Main-couple probabilities

Distribution first; then read low-probability topics that still carry conflict / secrecy
arc roles — those are the ones most likely to be external plot, not couple arc.

In [4]:
print(h6[["main_couple_prob", "non_couple_prob", "unclear_prob"]].describe())
fig, ax = plt.subplots(figsize=(6, 3.5))
ax.hist(h6["main_couple_prob"].dropna(), bins=20, color="steelblue", edgecolor="white")
ax.set_title("H6 main_couple_prob")
ctx.save_figure(fig, "h6_main_couple_hist")
plt.show()

low_mc = h6[h6["main_couple_prob"].fillna(0) < 0.4].copy()
print(f"Topics with main_couple_prob < 0.4: {len(low_mc)}")
if len(low_mc):
    display(
        rd.annotation_overview(low_mc, CODE_COL, extra_cols=["main_couple_prob"])[
            ["topic", "taxonomy", "code", "code_norm", "main_couple_prob"]
        ]
    )

       main_couple_prob  non_couple_prob  unclear_prob
count           54.0000          54.0000       54.0000
mean             0.7111           0.2296        0.0593
std              0.2941           0.2745        0.0196
min              0.1000           0.1000        0.0500
25%              0.8500           0.1000        0.0500
50%              0.8500           0.1000        0.0500
75%              0.8500           0.1000        0.0500
max              0.8500           0.8000        0.1000

  saved figure: results/stage11_refined_construct_analysis/v4_l12_granular_final_call49/notebook_analysis/06_h6_arc_semantics_audit/figures/h6_main_couple_hist.png
Topics with main_couple_prob < 0.4: 10

/tmp/ipykernel_99740/3171978054.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

                                    topic                                           taxonomy    code code_norm  main_couple_prob
0     121 — Revealing Plans to The Prince  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_0     ARC_0            0.1000
1           130 — Revealing A Secret Plan  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_0     ARC_0            0.1000
2           248 — Arranging A Cover Story  4.3 — Secrets, Misunderstandings & Hidden Info...  ARC_10    ARC_10            0.1000
3      286 — Trying to Regain Good Graces  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_0     ARC_0            0.1000
4  346 — Delivering Urgent News in Secret  4.3 — Secrets, Misunderstandings & Hidden Info...   ARC_0     ARC_0            0.1000
5            256 — Refusing to Let It End         4.4 — Conflict, Distance & Breakup Threats   ARC_0     ARC_0            0.1000
6   316 — Snapping Over Money and Control         4.4 — Conflict, Distance & Breakup Threats   ARC_0     ARC_0            0.1000
7               6 — Whispered Reassurance   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_0     ARC_0            0.1000
8           36 — Eagerly Offering to Help   4.6 — Emotional Safety, Reassurance & Caretaking   ARC_0     ARC_0            0.1000
9  338 — Promising Never to Do That Again      9.2 — Promise, Vow & Future-Tense Speech Acts   ARC_0     ARC_0            0.1000

## 4. Topic × position weights \(W_{tkr}\)

In [5]:
wtkr = nh.load_w_tkr(cfg)
print(f"W_tkr rows: {len(wtkr)}")
if not wtkr.empty:
    wtkr = wtkr.copy()
    wtkr["code_norm"] = wtkr["construct_code"].map(normalize_code)
    display(
        wtkr.groupby(["tertile", "code_norm"], dropna=False)["weight"]
        .mean()
        .unstack(fill_value=0)
        .round(3)
    )
    ctx.save_table(wtkr, "w_tkr_raw")

W_tkr rows: 266

code_norm  ARC_0  ARC_1  ARC_10  ARC_2  ARC_3  ARC_4  ARC_5  ARC_6  ARC_7  ARC_8  ARC_9
tertile
begin     0.7030 0.3690  0.6450 0.4180 0.5650 0.3560 0.5300 0.4300 0.7000 0.4950 0.5180
end       0.7000 0.4480  0.5970 0.4300 0.4470 0.4690 0.7200 0.5620 0.5130 0.3970 0.4500
middle    0.7510 0.3330  0.6580 0.4370 0.3060 0.3450 0.4980 0.5220 0.7000 0.7000 0.3920

  saved table: results/stage11_refined_construct_analysis/v4_l12_granular_final_call49/notebook_analysis/06_h6_arc_semantics_audit/tables/w_tkr_raw.csv  (266 rows)

## 5. Close reading

Force-include low main-couple topics. In the cards, watch tertile tags on sentences:
rising end-conflict that is non-couple should not feed REFINED_RISING the same way
main-couple conflict does.

In [6]:
review_ids = rd.select_review_topics(
    h6,
    hyp=HYP,
    lex_idx=lex_idx,
    ctx_idx=ctx_idx,
    adj_idx=adj_idx,
    force_ids=low_mc["topic_id"].tolist(),
    per_code=3,
    seed=42,
)
packs = rd.show_review_set(
    cfg,
    h6,
    review_ids,
    hyp=HYP,
    lex_idx=lex_idx,
    ctx_idx=ctx_idx,
    adj_idx=adj_idx,
    code_col=CODE_COL,
    max_sentences=10,
)
ctx.save_markdown(
    rd.render_review_markdown(packs, title="H6 arc semantics — close-reading pack"),
    "close_reading_pack",
)
ctx.save_table(
    h6[
        [
            "topic_id",
            "current_topic_label",
            "current_taxonomy_id",
            "current_taxonomy_name",
            "arc_role",
            "code_norm",
            "main_couple_prob",
            "non_couple_prob",
        ]
    ],
    "arc_topic_annotations",
)

Close-reading 54 of 54 topics (disagreements / mixed / manual / stratified sample).

============================================================================================
  TOPIC 6 — Whispered Reassurance
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : ARC_0  (norm: ARC_0)
  Stage08 snippets:
      · i’ll make sure of it,” he whispered.
      · you’ll be fine,” he whispered. “
      · quiet, subdued, she nodded and then, “you’ll be safe.”
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=end, p=0.62]
        Ian stared right back and asked slowly, clearly, enunciating every word, “Who asked
        you to?”
    · [BOOK_002, CELL_D, tertile=middle, p=0.74]
        Okay,’ she said, striving for a light tone in the heavy silence. ‘
  Pass A/B/C:
    A lexical: ARC_10
        All four keyword lists describe speech-act mechanics and vocal/emotional
        delivery cues (whispered, softly, tentatively, hesitation, drawled, solemnly,
        eagerly, confessed, mumbled) without anchoring to any specific relational event
        between a main couple. 'Confessed' and 'tentatively' could hint at disclosure or
        conflict, but no keyword cluster points clearly to a defined arc
    B contextual: ARC_0
        Every sentence in this topic is a decontextualized dialogue fragment consisting
        solely of minimal affirmative or acknowledgment tokens ('Yes,' 'Okay,' 'Oh,'
        'she said,' 'she asks,' 'he replies,' etc.) with no surrounding narrative
        content. There is no identifiable subject matter, no relational dynamic, no
        character identification, and no arc-relevant content whatsoever. The topic
    C adjudicate: ARC_0 action=EXCLUDE_FROM_HYPOTHESIS
        The contextual dominant judgment (ARC_0) holds. Taxonomy label 4.6 Emotional
        Safety, Reassurance & Caretaking and Radway codes R8/R9/R10 (tender hero
        treatment, heroine's emotional response) describe a general affective register —
        tenderness and caretaking — rather than a specific arc function that implicates
        the main couple's relational trajectory. Per critical rules, ARC_7 requires

============================================================================================
  TOPIC 36 — Eagerly Offering to Help
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : ARC_0  (norm: ARC_0)
  Stage08 snippets:
      · of course, i’ll help you.’
      · then you’ll let me help,” frances said at once, her expression eager. “
      · sure, of course, i’ll help.”
  Novel sentences:
    · [BOOK_001, CELL_B, tertile=end, p=0.80]
        And you know I’m here to help you in any way I can.”
    · [BOOK_002, CELL_D, tertile=middle, p=0.57]
        Well make yourself useful,” he said. “
    · [BOOK_001, CELL_B, tertile=end, p=0.76]
        I’ve got to do something to help.”
  Pass A/B/C:
    A lexical: ARC_0
        All four keyword lists center on transactional assistance and task-oriented
        language: 'help, need, assistance, thanks, helped' (Main); 'provided, willing,
        appreciate, replies, eagerly, requested, task, promptly, sir' (KeyBERT); 'task,
        options, success, terms, sentence, pleased, excited' (POS); 'mister, promptly,
        appreciate, eagerly, options, success, intend, insisted, pleased' (MMR). None of
    B contextual: ARC_0
        Topic 36 consists entirely of generic, decontextualized offers and requests for
        help ('Can I help you?', 'Let me help you.', 'I'll help.'). These fragments
        carry no identifiable speaker, recipient, or relational context. There is no
        evidence that the main romantic couple is implicated in any of these utterances,
        nor that any romantic relationship state is being changed. The topic appears to
    C adjudicate: ARC_0 action=KEEP
        All three evidence streams — lexical consensus (ARC_0), contextual dominant
        (ARC_0), and the taxonomy/Radway/Stage11 labels — converge. The taxonomy places
        this in Emotional Safety, Reassurance & Caretaking, and the Radway codes (R8
        hero treats heroine tenderly, R9, R10) describe affective texture rather than a
        relational arc function. Stage11 codes (RAX_emotional_reassurance,

============================================================================================
  TOPIC 121 — Revealing Plans to The Prince
============================================================================================
  Taxonomy : 4.3 — Secrets, Misunderstandings & Hidden Information
  Code     : ARC_0  (norm: ARC_0)
  Stage08 snippets:
      · she’ll be queen of the roost.” “
      · do you think he’ll really go to the king?”
      · if i let the prince know what is happening, instead of waiting for them to find out,
      · they’ll know i’ve been out on my own.
  Novel sentences:
    · [BOOK_001, CELL_C, tertile=middle, p=0.49]
        I am not Prince Charming or a shining Knight on a white horse.
    · [BOOK_001, CELL_C, tertile=middle, p=0.40]
        Hot as a fever, rattling bones I could just taste it, taste it If it’s not forever,
        if it’s just tonight Oh it’s still the greatest, the greatest, the greatest Kings of
        Leon Chapter Ten “You two pieces of shit are worthless you know that?”
    · [BOOK_001, CELL_C, tertile=end, p=0.38]
        I WILL one day go on a vacation to Disneyland and actually hang with Belle, Beast,
        Briar, Winter and Ashess.
  Pass A/B/C:
    A lexical: ARC_9
        Main keywords (king, prince, queen, throne, servant, royal, crown, kingdom,
        regent) are densely royal/political — no main-couple romantic arc signal,
        pointing to external political/power-structure conflict (ARC_9). MMR reinforces
        this with 'threats', 'declared', 'resigned', 'dealing', 'commander' — language
        of political negotiation and power struggle rather than romantic arc. KeyBERT
    B contextual: ARC_0
        Topic 121 clusters around royalty/nobility vocabulary — kings, queens, nobles,
        rulers — but this is overwhelmingly world-building or external-political context
        rather than main-couple romantic arc content. BOOK_001 sentences are off-target
        (pop-culture references, fairy-tale tropes with no couple dynamic). BOOK_002
        sentences revolve around a king's treachery/political machinations with no
    C adjudicate: ARC_0 action=REINTERPRET
        Adjudication resolves the conflict between lexical consensus (ARC_9:
        external_plot_conflict) and contextual dominant (ARC_0: off_target) in favor of
        ARC_0. The taxonomy placement under 4.3 Secrets, Misunderstandings & Hidden
        Information with a secondary tag of 10.2 Historical & Period Setting suggests
        the topic's surface signal is period/setting detail or background intrigue
    !! manual_review_required

============================================================================================
  TOPIC 130 — Revealing A Secret Plan
============================================================================================
  Taxonomy : 4.3 — Secrets, Misunderstandings & Hidden Information
  Code     : ARC_0  (norm: ARC_0)
  Stage08 snippets:
      · you’ve rumbled my clever plan.’ ‘
      · yes, i’ve got a little more planned for this evening.
      · we’ve had this planned for months, but i’d almost forgotten about it.
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=middle, p=0.54]
        She would come out with mad plans and then challenge me into doing them.
    · [BOOK_002, CELL_B, tertile=begin, p=0.68]
        I had a real and viable plan in place now to turn things around.
    · [BOOK_002, CELL_B, tertile=middle, p=0.62]
        This plan—it's not going to get you into any trouble at school?” “
  Pass A/B/C:
    A lexical: ARC_10
        All four keyword lists center on planning and logistics vocabulary: 'plan,
        plans, planned, planning, tentatively, considering, scenario, urgency,
        according, part.' Supporting terms like 'madam, sir, reception, results,
        pumping, veins, forming, hiding, opposite' add situational texture but do not
        anchor to any specific narrative-arc role for the main couple. There is no clear
    B contextual: ARC_0
        Topic 130 is entirely about the word 'plan(s)' and logistical planning language.
        None of the sentences carry any identifiable romantic-arc function — there is no
        conflict, disclosure, repair, commitment, or other arc-relevant content. The
        sentences are decontextualised fragments about making or changing plans, with no
        clear main-couple relationship dynamic visible. The topic is off-target (ARC_0)
    C adjudicate: ARC_0 action=REINTERPRET
        Adjudication resolves the Pass A/B tension as follows: the lexical consensus of
        ARC_10 (unclear arc role) reflects genuine ambiguity in surface tokens, but the
        contextual dominant of ARC_0 (off_target) is better supported by the taxonomy
        signal. Taxonomy 4.3 (Secrets, Misunderstandings & Hidden Information) with
        secondary 4.2 (Ongoing Courtship & Everyday Relational Bonding) describes

============================================================================================
  TOPIC 248 — Arranging A Cover Story
============================================================================================
  Taxonomy : 4.3 — Secrets, Misunderstandings & Hidden Information
  Code     : ARC_10  (norm: ARC_10)
  Stage08 snippets:
      · i can attach myself to callie as a potential suitor, even with the distant cousin
      · story you’ve decided to run with.
      · i'll just let hannah know she won't have to watch him after today.
      · it means you’ll probably bump into him too if you see more of hannah.’
  Novel sentences:
    · [BOOK_001_begin, CELL_B, tertile=begin, p=0.66]
        That Hannah’s boyfriend was sleeping with apparently the whole time they were going
        out?
    · [BOOK_001_begin, CELL_B, tertile=begin, p=0.65]
        On Hannah’s behalf, and on yours too, even though I didn’t know your name.”
    · [BOOK_001_begin, CELL_B, tertile=begin, p=0.64]
        Hannah took me to that party as a pity thing, unfortunately.
    · [BOOK_001_begin, CELL_B, tertile=begin, p=0.64]
        Including that hot guy Hannah had started to introduce me to.
    · [BOOK_003_middle, CELL_C, tertile=middle, p=0.47]
        Evan,” she says, “that day, last week, I went out to the pond, it was the day after
        the bear.
    · [BOOK_005_middle, CELL_A, tertile=middle, p=0.56]
        Anyway, I was totally pissed about that, and about Jess pinching my arm, when Cassie
        dropped another bomb on me… She said that she is “Falling in love with Jimmy!!!!”
    · [BOOK_005_middle, CELL_A, tertile=middle, p=0.54]
        Getting all mad because of her relationship with Jimmy… Wishing that they had never
        started dating… Now I will never see Cassie again!
    · [BOOK_005_middle, CELL_A, tertile=middle, p=0.54]
        Jess and I rode together, but Cassie said she would meet us there; she was still
        trying to find the perfect gift for Jimmy.
  Pass A/B/C:
    A lexical: ARC_10
        Main and POS are dominated by character names (callie, hanna, leslea), a
        pickpocketing incident, and abstract nouns (concept, notion, options, treatment)
        with no clear romantic-arc signal — coded ARC_0 (off-target). KeyBERT and MMR
        carry emotionally loaded cues (crushed, upset, pregnant, admit, overheard,
        apologize, problems, wasting) that suggest distress and possible disclosure, but
    B contextual: ARC_10
        Topic 248 clusters around the name 'Hannah' and secondary character names
        (Cassie, Jimmy, Jess, Amy). No single main couple is clearly established across
        sentences. BOOK_001 sentences reference Hannah's cheating boyfriend — a third-
        party relationship conflict, coded ARC_9. BOOK_003 sentences involve an external
        rescue/intel operation with no romantic couple visible, coded ARC_9. BOOK_004
    C adjudicate: ARC_10 action=KEEP
        Both lexical consensus and contextual dominant converge on ARC_10
        (unclear_arc_role). The taxonomy placement under 4.3 Secrets, Misunderstandings
        & Hidden Information suggests latent ARC_1 or ARC_5 signal, but without
        sufficient topic-word or passage evidence to override the double ARC_10 signal,
        reinterpretation would be speculative. The secondary taxonomy tag (5.2 Friends,
    !! manual_review_required

============================================================================================
  TOPIC 256 — Refusing to Let It End
============================================================================================
  Taxonomy : 4.4 — Conflict, Distance & Breakup Threats
  Code     : ARC_0  (norm: ARC_0)
  Stage08 snippets:
      · no, i’ll get over it.
      · i’ll give you some time, but goddamn it, nat, this is not over.”
      · it’ll never be over—unless it ends right here right now.
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=begin, p=0.45]
        I no longer cared which side won or lost, I only wanted it to be over.
    · [BOOK_002, CELL_D, tertile=middle, p=0.48]
        Perhaps when this is over, you might see another attractive alternative.
    · [BOOK_002, CELL_D, tertile=end, p=0.44]
        If there are consequences to our lovemaking, then this treasure hunt ends.
  Pass A/B/C:
    A lexical: ARC_4
        Main keywords ('end', 'over', 'ends', 'ended') strongly suggest termination or
        breakup language pointing toward ARC_3 (separation/breakup threat). However,
        KeyBERT, POS, and MMR all add affective-distress cues — 'hurts', 'anxious',
        'shouted', 'repeated', 'sending' — that shift the dominant signal toward ongoing
        emotional suffering within or caused by the relationship (ARC_4:
    B contextual: ARC_0
        Topic 256 is dominated by the word 'over' used in highly varied, mostly non-
        romantic-arc senses: completion of events, wars, tasks, emotional recovery, and
        social pleasantries. The largest single cluster (ARC_0, ~45%) consists of
        sentences where 'over' has no clear romantic-arc meaning. A secondary cluster
        from BOOK_004 uses 'I'm over it / get over it' language that loosely implies
    C adjudicate: ARC_0 action=REINTERPRET
        Lexical consensus (ARC_4) reflects surface conflict-label fidelity to taxonomy
        4.4 (Conflict, Distance & Breakup Threats), but the contextual dominant code
        (ARC_0) indicates the topic content does not actually center on the main
        couple's relationship-caused distress. The taxonomy placement in 4.4 is a label
        match, not a content match. Because high conflict-label fidelity ≠ main-couple
    !! manual_review_required

============================================================================================
  TOPIC 286 — Trying to Regain Good Graces
============================================================================================
  Taxonomy : 4.3 — Secrets, Misunderstandings & Hidden Information
  Code     : ARC_0  (norm: ARC_0)
  Stage08 snippets:
      · oh ms. [person], you really should drop by our office more, we miss your good taste
      · around here' blah blah blah.
      · i'll not have you and his grace at each other's throats before we arrive at champney
      · court."
      · if what you’ve said is to be believed, how am i supposed to get back into her good
      · graces?
  Novel sentences:
    · [BOOK_003, CELL_A, tertile=begin, p=0.53]
        Widow of a respected insurance agent and former daughter-in-law of a well-known
        Baptist minister, she’d seemingly shunned the social position and privilege of her
        past to be with Colton, but this wasn’t the first time Eric had seen her slip on her
        high-and-mighty act like an expensive fur coat.
    · [BOOK_003, CELL_A, tertile=begin, p=0.48]
        Eric needed a mentor to teach him how to be an honorable man.
  Pass A/B/C:
    A lexical: ARC_0
        Main keywords are dominated by proper nouns and names (graceclemens, ruttery,
        champney, oracle, grâce) with no clear romantic-arc signal; 'blah' and 'tape'
        add noise. KeyBERT offers 'thrilled', 'embarrassment', 'awkwardly', 'deserve' —
        mild emotional texture but no identifiable main-couple dynamic; 'dr' and
        'continues' are generic. POS and MMR introduce 'desperation', 'embarrassment',
    B contextual: ARC_0
        Topic 286 clusters around proper-noun name references (Mrs. Darden, His Grace,
        Reed, Eric, Dee, Cynda) and brief honorific/address fragments. None of the
        sentences establish a clear main-couple romantic arc dynamic. BOOK_001–003
        sentences involve secondary or peripheral characters (Eric, Dee, Cynda, Colton)
        with no identifiable main-couple romantic conflict or progression. BOOK_004
    C adjudicate: ARC_0 action=KEEP
        Both lexical consensus and contextual dominant agree on ARC_0 (off_target). The
        taxonomy tag 4.3 Secrets/Misunderstandings and secondary 3.2 Negative Emotions
        might superficially suggest ARC_1 or ARC_4, but the main-couple filter is not
        satisfied — the topic does not pertain to the primary romantic dyad. Without a
        main-couple anchor, secrets or distress signals cannot be coded as relationship-

============================================================================================
  TOPIC 316 — Snapping Over Money and Control
============================================================================================
  Taxonomy : 4.4 — Conflict, Distance & Breakup Threats
  Code     : ARC_0  (norm: ARC_0)
  Stage08 snippets:
      · you’ll have to find another way to obtain the tallmadge money,” lucas snapped. “
      · stop that, you little fool, otherwise we’ll both be—’ lucas began, and then stopped
      · as one of suzy’s flailing hands caught the side of his mouth.
      · they didn’t like it much when they found out, but lucas paid them well, and they’ll
      · get over it.
  Novel sentences:
    · [BOOK_002, CELL_B, tertile=middle, p=0.59]
        Perhaps you should show Eva to her room,” Lucas finally suggested to Michael. “
    · [BOOK_002, CELL_B, tertile=middle, p=0.49]
        Unlike Ethan and Jason, who were dark-haired, Aaron and Lucas were more dirty-
        blonde.
    · [BOOK_006, CELL_B, tertile=end, p=0.64]
        He watched Lucas Mason as he spoke and was rewarded by an expression of guilt upon
        his uncle’s face. “
    · [BOOK_006, CELL_B, tertile=end, p=0.55]
        You have brought this upon us,” Lucas Mason harshly accused his grief stricken
        nephew. “
    · [BOOK_006, CELL_B, tertile=end, p=0.55]
        Lucas Mason was not so wise, however, and questioned Rork angrily. “
    · [BOOK_006, CELL_B, tertile=end, p=0.51]
        The look upon Lucas Mason’s traitorous face mirrored the truth of Rork’s words.
    · [BOOK_006, CELL_B, tertile=end, p=0.51]
        But as Lucas continued his tirade, Rork reached out to touch his beloved father’s
        body , only to find it frozen.
  Pass A/B/C:
    A lexical: ARC_4
        All four keyword lists converge on emotional distress and negative affect within
        a relationship context. Main keywords (stared, thoughtful, shout, named
        characters lucas/fallon) suggest interpersonal tension between identifiable
        parties. KeyBERT supplies the emotional valence: annoyance, groaned,
        disappointment, failure, pathetic — these are feelings generated by the
    B contextual: ARC_0
        Topic 316 clusters around the name 'Lucas' (and associated characters Aaron,

============================================================================================
  TOPIC 157 — Swearing to Save Him From Himself
============================================================================================
  Taxonomy : 4.5 — Reconciliation, Commitments & HEA
  Code     : ARC_7  (norm: ARC_7)
  Stage08 snippets:
      · and you’ll get it, i swear,” [person].
      · if [person] sees me like this, i'll die."
      · and i might be young but i guess that just makes me lucky… i do love him and whether
      · i have your help or not, i have to save him from himself… i know [person], i know
  Novel sentences:
    · [BOOK_006, CELL_B, tertile=middle, p=0.73]
        Sam couldn’t understand it, and that bothered him.
    · [BOOK_001, CELL_B, tertile=begin, p=0.82]
        What else had Sam witnessed?
    · [BOOK_006, CELL_B, tertile=begin, p=0.80]
        Sam noticed stuff like that.
  Pass A/B/C:
    A lexical: MIXED
        Main keywords (samantha, samara, sammi, name, optimism, jonathan) suggest
        character naming/identification with ambiguous relational valence — ARC_10.
        KeyBERT (begged, confessed, willing, tense, brief) points toward a disclosure or
        confession moment — ARC_5. POS (dislike, worries, desperation, embarrassing,
        gritted) suggests emotional distress tied to the relationship — ARC_4. MMR
    B contextual: ARC_0
        Topic 157 is a character-name topic centered entirely on the name 'Sam'
        appearing in minimal sentence fragments (dialogue tags, address forms, brief
        attributions). The sentences contain no relational content, no couple dynamics,
        no conflict, no disclosure, no commitment — they are purely
        syntactic/attribution fragments. The one marginally notable sentence ('Sam,
    C adjudicate: ARC_7 action=REINTERPRET
        The lexical consensus (MIXED) and contextual dominant (ARC_0) are overridden by
        the convergent weight of the metadata signals. Taxonomy 4.5 (Reconciliation,
        Commitments & HEA), Radway R11 (hero declares love and demonstrates commitment),
        R9, and R13, together with Stage11 codes RAX_emotional_reassurance and
        RAX_emotional_security, all point consistently toward a trust-restoration and

============================================================================================
  TOPIC 175 — Gentleman Offers Steadying Support
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : ARC_7  (norm: ARC_7)
  Stage08 snippets:
      · the occurrences of the day were too full of interest to leave elizabeth much
      · attention for any of these new friends; and she could do nothing but think, and
      · mr. [person] placed his hand on [person]’s shoulder for support as mr. [person]
      · barely walked out the front door.
      · yes, but when i fell ill, it was apparent that i could not travel all the way to
      · calais, so mr. [person] took me to the house of a friend of his: mr. [person].”
  Novel sentences:
    · [BOOK_001, CELL_B, tertile=end, p=0.51]
        On his way to see Mistress Gwyllain to explain your…ah, unexplained arrival.”
    · [BOOK_003, CELL_B, tertile=begin, p=0.51]
        Shit," grunted Sheridan, apparently immune to Owen's considerable charms. "
  Pass A/B/C:
    A lexical: ARC_4
        Main keywords (mr, bingley, miss, georgiana, bennet, pemberley) point to
        secondary characters and social settings from Pride and Prejudice, suggesting
        peripheral or ensemble content with no clear romantic-arc signal — coded ARC_0.
        However, KeyBERT, POS, and MMR all converge on emotional distress vocabulary:
        'worrying,' 'uncomfortably,' 'distress,' 'longing,' 'struggling,' 'passionate,'
    B contextual: ARC_10
    C adjudicate: ARC_7 action=REINTERPRET
        The lexical consensus (ARC_4) flags relationship-caused distress, and the
        contextual judgment (ARC_10) flags ambiguity, but the supporting metadata
        strongly points away from both. Taxonomy 4.6 (Emotional Safety, Reassurance &
        Caretaking) combined with Radway R8 (hero treats heroine tenderly) and Stage11
        RAX_emotional_reassurance collectively describe a scene in which the hero
    !! manual_review_required

============================================================================================
  TOPIC 177 — Seeing Past A Hidden Identity
============================================================================================
  Taxonomy : 4.3 — Secrets, Misunderstandings & Hidden Information
  Code     : ARC_1  (norm: ARC_1)
  Stage08 snippets:
      · you’ll no longer be alex.
      · i know they say if you want something bad enough you’ll find any excuse to believe
      · it’s true… but there was something in alex that called to me.
      · tell me you understand that, or you’ll be no help to alex.”
  Novel sentences:
    · [BOOK_003, CELL_B, tertile=middle, p=0.58]
        In the midst of my pleasure at seeing Alejandro literally backed up against a wall,
        I felt a pinprick of irritation at Jonno’s inability to see Eve as she was.
    · [BOOK_003, CELL_B, tertile=end, p=0.56]
        I couldn’t get what she’d said about Alejandro out of my head.
    · [BOOK_003, CELL_B, tertile=middle, p=0.53]
        I still couldn’t believe that she had been with Alejandro last night.
    · [BOOK_004, CELL_B, tertile=middle, p=0.76]
        It was ironic that he should do this now, when the last person she wanted to think
        about was Alex. ‘
  Pass A/B/C:
    A lexical: ARC_10
        Main keywords (sullivan, alexx, alexi, eliminate, woo, wanted, wasn, tell)
        suggest character names and vague action verbs with no clear romantic-arc
        signal; 'eliminate' and 'woo' are ambiguous without context. KeyBERT (instincts,
        realise, suffering, unsure) hints at internal emotional uncertainty but does not
        anchor to a specific arc stage. POS and MMR (dislike, guarded, fears, instincts,
    B contextual: ARC_2
        Topic 177 clusters around a named third-party figure ('Alex'/'Alejandro') who
        generates tension, jealousy, and friction between protagonists and their
        partners. The dominant signal is escalating interpersonal conflict (ARC_2):
        snapping, jealousy over Alejandro, complaints about Alex, and suspicion. One
        sentence shows a separation/withdrawal threat (ARC_3: Eve moving toward
    C adjudicate: ARC_1 action=REINTERPRET
        Lexical consensus was ARC_10 (unclear) and contextual dominant was ARC_2
        (escalation_conflict), but the taxonomy metadata resolves the ambiguity: the
        primary taxonomy is 4.3 Secrets, Misunderstandings & Hidden Information. Hidden
        information and secrets are the structural driver here, making ARC_1
        (misunderstanding) the most precise fit — misunderstandings in romance arcs are

============================================================================================
  TOPIC 210 — Expelled For Pursuing A Relationship
============================================================================================
  Taxonomy : 4.4 — Conflict, Distance & Breakup Threats
  Code     : MIXED
  Stage08 snippets:
      · she’ll be back,” [person] to explain.
      · we’ll not last long like this,” [person] said quietly.
      · if you pursue a relationship with [person], you’ll be expelled from motherhouse
      · ireland, removed from your triad, and cast out from our way of life.
  Novel sentences:
    · [BOOK_002, CELL_B, tertile=begin, p=0.54]
        And, she’d reasoned, if pop star Jessica Simpson could resist the delectable Nick
        Lachey until their wedding night, she could certainly resist John.
    · [BOOK_002, CELL_B, tertile=end, p=0.49]
        Besides, if there was one thing she’d come to know about Zeke, it was that he was
        able to make every audience member feel connected to him.
    · [BOOK_002, CELL_B, tertile=end, p=0.48]
        Patrick huffed, as though he couldn’t believe Zeke had the audacity to claim that
        he—the up-by-his-boot-straps, self-made founder of a publishing empire—had anything
        in common with a bad-boy rock star.
    · [BOOK_002, CELL_B, tertile=middle, p=0.44]
        As a waiter moved away with their plates, John said, “By the way, I saw that Scarlet
        was linked to Zeke Woodlow in today’s gossip columns.
    · [BOOK_002, CELL_B, tertile=end, p=0.40]
        Unfortunately, a celebrity of Zeke’s caliber has an image to maintain and a
        publicity machine that needs to be fed—with the right kind of publicity, of course.”
        “
    · [BOOK_004, CELL_C, tertile=begin, p=0.35]
        The Hole was owned by a man named Peter Rabbit to the chagrin of his wife, Petra.
    · [BOOK_006, CELL_B, tertile=begin, p=0.51]
        Some would think that when swimming in the depths of one’s own grief, one could
        forget what it was that made them so unhappy, but tell that to Nathaniel.
    · [BOOK_006, CELL_B, tertile=middle, p=0.50]
        Either way, there was something exhilarating about being with Nathaniel, especially
        being with him in his lair.
    · [BOOK_006, CELL_B, tertile=middle, p=0.50]
        For the life of him, Nathaniel didn’t know how Mr. Harrington was a part of his
        beauteous bride-to-be’s biological makeup.
    · [BOOK_006, CELL_B, tertile=begin, p=0.42]
        Nathaniel had come to understand and grudgingly accept that fact.
  Pass A/B/C:
    A lexical: ARC_6
        KeyBERT and MMR both surface 'forgive,' 'afterward,' and 'instincts,' pointing
        toward a repair attempt following friction. MMR adds 'unwilling' and
        'annoyance,' suggesting resistance to reconciliation but still within a repair
        arc. POS keywords ('disappointment,' 'annoyance,' 'unwilling,' 'distraction')
        lean toward ongoing relational distress (ARC_4), and Main keywords ('didn,'
    B contextual: MIXED
        Topic 210 spans multiple books and narrative threads. BOOK_008 sentences
        dominate numerically and consistently reference a past relationship with 'Nick'
        that has ended or is being discussed as over, coding as ARC_3
        (separation/breakup threat). BOOK_009 shows a couple in active conflict (Drake
        slamming out), coding as ARC_2. BOOK_006 involves emotional distress around
    C adjudicate: MIXED action=REINTERPRET
        Lexical consensus (ARC_6 repair) and contextual dominant (MIXED) diverge.
        Taxonomy 4.4 (Conflict, Distance & Breakup Threats) with secondary 5.1 (Family,
        Kinship & Parenthood) suggests the topic straddles active repair attempts and
        ongoing separation/breakup threat pressures — likely a moment where the couple
        is trying to reconcile but family-related conflict is simultaneously threatening
    !! manual_review_required

============================================================================================
  TOPIC 214 — Demanding to Know What Happened
============================================================================================
  Taxonomy : 4.3 — Secrets, Misunderstandings & Hidden Information
  Code     : ARC_1  (norm: ARC_1)
  Stage08 snippets:
      · oh my god, how did this happen?”
      · please, tell me precisely what is happening to you.”
      · and i need to know what’s going on to some extent so i don’t think the worst.
  Novel sentences:
    · [BOOK_002, CELL_D, tertile=end, p=0.71]
        Damn you…tell me what happened!”
    · [BOOK_002, CELL_D, tertile=middle, p=0.67]
        What the hell has she done?”
    · [BOOK_002, CELL_D, tertile=middle, p=0.70]
        What has happened to you?”
  Pass A/B/C:
    A lexical: ARC_2
        KeyBERT, POS, and MMR all converge on escalation cues: 'caused/causing' (active
        harm in progress), 'worst' (peak negative intensity), 'extent' (measuring
        severity of damage), and 'precisely/honestly' (confrontational demand for
        truth). Main keywords ('hell, fuck, what happened, going, happening') are
        emotionally charged interrogatives signaling a heated confrontation or crisis
    B contextual: ARC_10
        All sentences in Topic 214 are short, decontextualized interrogative fragments
        ('What happened?', 'What's going on?', 'What the hell happened?'). They express
        reactive surprise or demand for information but carry no identifiable narrative
        arc role on their own — there is no indication of who is speaking, to whom, or
        in what relational context. No sentence can be reliably linked to a main couple,
    C adjudicate: ARC_1 action=REINTERPRET
        Lexical consensus (ARC_2 escalation_conflict) and contextual dominant (ARC_10
        unclear) diverge, but the taxonomy anchor — 4.3 Secrets, Misunderstandings &
        Hidden Information — is the decisive tie-breaker. Hidden information and secrets
        are the structural engine of ARC_1 (misunderstanding), not ARC_2 (escalation) or
        ARC_10 (unclear). ARC_2 would require evidence that conflict is actively

============================================================================================
  TOPIC 237 — Hiding Someone Before He Arrives
============================================================================================
  Taxonomy : 4.3 — Secrets, Misunderstandings & Hidden Information
  Code     : ARC_5  (norm: ARC_5)
  Stage08 snippets:
      · i’ll call jared now.
      · jared was just heading off to work but is going to need his shirt so i’ll be right
      · back.”
      · you can’t come because if jared catches one glimpse of you, he’ll know.
  Novel sentences:
    · [BOOK_001, CELL_C, tertile=end, p=0.41]
        At that, several male heads popped out, one of them being Ronald, Dee’s boyfriend.
    · [BOOK_002, CELL_A, tertile=end, p=0.53]
        PJ," Garrett says, "how many times are you going to make me ask you to call me
        Garrett?" "
    · [BOOK_002, CELL_A, tertile=begin, p=0.52]
        Something is happening inside Garrett's head, a feeling so bizarre he can't quite
        place it, can't put a name to it.
  Pass A/B/C:
    A lexical: ARC_4
        Main rep leans toward interpersonal conflict via 'wrathfully', 'eyed', and named
        male characters in apparent confrontation, suggesting ARC_2 escalation. However,
        KeyBERT, POS, and MMR converge strongly on ARC_4 (relationship-caused distress):
        POS offers 'distress', 'disbelief', 'disappointed', 'wound', 'fingertips'
        (physical/emotional hurt); MMR reinforces with 'distress', 'collapsed',
    B contextual: ARC_10
        Topic 237 is dominated by fragmentary dialogue tags and brief action snippets
        (e.g., 'Jared queried', 'Jared shrugged', 'Garrett feels his face flush', 'Keep
        him coming') that provide no discernible narrative-arc signal. The sentences are
        almost entirely decontextualised speech-attribution fragments or minor physical
        actions. No clear main couple is identifiable across the books — BOOK_001
    C adjudicate: ARC_5 action=REINTERPRET
        Lexical consensus (ARC_4: relationship_caused_distress) and contextual dominant
        (ARC_10: unclear_arc_role) are in tension. The taxonomy anchor — 4.3 Secrets,
        Misunderstandings & Hidden Information — provides the decisive tiebreaker.
        Hidden information and secrets are the structural engine of ARC_5 (disclosure),
        not merely ambient distress (ARC_4) or an unresolved arc role (ARC_10). The
    !! manual_review_required

============================================================================================
  TOPIC 240 — Unsure How to Offer Comfort
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : ARC_7  (norm: ARC_7)
  Stage08 snippets:
      · oh my god, sean!
      · sean pursed his lips, unsure he was equal to the task of comforting [person].
      · sean held out his hand and added; “now if you’ll excuse me i have a beautiful woman
      · waiting to have breakfast with me.”
  Novel sentences:
    · [BOOK_002, CELL_B, tertile=begin, p=0.50]
        Oh,” I said, thinking fast, watching as Seth started to show Liam how to use another
        nearby machine, while the Tiffanys and Brittanys gathered round, looking more
        worshipful than ever.
    · [BOOK_003, CELL_B, tertile=end, p=0.48]
        You need to stop nipping at him and face the fact that when Shon goes under, he’s
        off limits, one breath away from being a hostile at our backs.” “
  Pass A/B/C:
    A lexical: ARC_10
        The keyword sets contain character names (sean, jaime, bryan, yseult, morrissey)
        and dialogue/reaction cues (answered, said, looked, mumbled, solemnly, absently,
        winced, patted, shivered, ducked) alongside emotional/cognitive states (anxious,
        unsure, conscious, distracted, curious). None of these cues point clearly to a
        specific arc function: there is no evidence of conflict escalation, disclosure,
    B contextual: ARC_0
        Every sentence in this topic is a degenerate fragment consisting solely of a
        character name ('Sean') followed by a dialogue tag or brief action ('asked.',
        'said,', 'shrugged.', 'met his gaze.', etc.) with no surrounding context. The
        topic appears to be a BERTopic artifact capturing a character-name/dialogue-
        attribution pattern rather than any meaningful narrative content. There is no
    C adjudicate: ARC_7 action=REINTERPRET
        The lexical consensus (ARC_10) and contextual dominant (ARC_0) both suggest
        ambiguity or irrelevance to the main couple arc, but the full metadata package
        strongly contradicts that reading. Taxonomy 4.6 (Emotional Safety, Reassurance &
        Caretaking) with secondary 4.2 (Ongoing Courtship & Everyday Relational
        Bonding), Radway R8 (Hero treats heroine tenderly) and R9, and Stage11 codes
    !! manual_review_required

============================================================================================
  TOPIC 247 — Promising You Will Not Be Alone
============================================================================================
  Taxonomy : 4.6 — Emotional Safety, Reassurance & Caretaking
  Code     : ARC_7  (norm: ARC_7)
  Stage08 snippets:
      · if we make it through this alone, we’ll just be better at being alone.”
      · you’ll never be alone.
      · before you say no, i want you to know i’ll be alone mostly.
  Novel sentences:
    · [BOOK_003, CELL_B, tertile=end, p=0.67]
        If I went out alone, it seemed I felt surrounded by people who couldn’t speak to me.
    · [BOOK_003, CELL_B, tertile=begin, p=0.66]
        I promise you, you will never be alone again so long as I live.”
    · [BOOK_003, CELL_B, tertile=begin, p=0.64]
        I’ve pictured this so many times in my mind, I don’t want to wake up and find I’m
        alone again.” “
  Pass A/B/C:
    A lexical: ARC_3
        Main keywords ('alone', 'solitude', 'rather', 'prefer', 'don', 'live here')
        strongly suggest a character expressing a desire for separation or withdrawal —
        classic separation/distance language. MMR reinforces this with 'chose',
        'insisted', 'planned', 'preferred', 'circumstances', 'fault' — implying a
        deliberate decision about the relationship's continuation under difficult
    B contextual: ARC_4
    C adjudicate: ARC_7 action=REINTERPRET
        The lexical consensus (ARC_3) and contextual dominant (ARC_4) both point toward
        distress or deterioration, but the full metadata picture contradicts that
        reading. Taxonomy 4.6 (Emotional Safety, Reassurance & Caretaking) with

============================================================================================
  TOPIC 285 — Confessing Years of Hatred
============================================================================================
  Taxonomy : 3.2 — Negative Emotions & Distress
  Code     : ARC_2  (norm: ARC_2)
  Stage08 snippets:
      · i’ve hated him for years.
      · heath has done a wonderful job with him, but i—well, i’ve hated him for living
      · instead of you.
      · ever since this cunt came here, i’ve been, uh, less than balanced, i admit, and
      · remembering things i’ve tried to forget, reasons to hate, reasons to hate, and
  Novel sentences:
    · [BOOK_001, CELL_C, tertile=middle, p=0.57]
        Looking back now, I can see all the hatred I had in me, but at the time it just
        seemed like everyone was out to get me.
    · [BOOK_001, CELL_C, tertile=end, p=0.48]
        It had been a long time since his presence had evoked disdain.
    · [BOOK_002, CELL_B, tertile=middle, p=0.62]
        And I hated submitting to your licentious thoughts and advances!” “
  Pass A/B/C:
    A lexical: ARC_5
        Main keywords ('hate', 'hated', 'hates', 'hating', 'hateful', 'myself') point
        strongly to internalized negative emotion directed at self or partner,
        suggesting relationship-caused distress (ARC_4). However, KeyBERT and MMR both
        surface 'admit', 'dislike', 'treated', 'deserve', and 'planning', which
        collectively signal a moment of confession or acknowledgment — a character
    B contextual: ARC_2
        Topic 285 is saturated with hatred, loathing, and disdain language ('I hate
        you', 'hated him', 'loathed him', 'dislike'). All sentences express intense
        interpersonal hostility, which maps cleanly to ARC_2 (escalation_conflict) — the
        emotional peak of antagonism between characters. The topic is not about
        misunderstanding (ARC_1), separation (ARC_3), or external plot (ARC_9); it is
    C adjudicate: ARC_2 action=REINTERPRET
        Lexical consensus flagged ARC_5 (disclosure), but the contextual dominant signal
        is ARC_2 (escalation_conflict), which better captures the taxonomy metadata:
        Negative Emotions & Distress (3.2) as primary and Interpersonal Non-Romantic
        Conflict (7.1) as secondary. The secondary taxonomy tag initially pulled toward
        ARC_5 (a disclosure event can surface distress), but disclosure is not the

============================================================================================
  TOPIC 301 — Confessing A Thin Relationship History
============================================================================================
  Taxonomy : 4.3 — Secrets, Misunderstandings & Hidden Information
  Code     : ARC_1  (norm: ARC_1)
  Stage08 snippets:
      · you know that because you’ve been with one other guy and had a long-term
      · relationship?
      · because one way or another it has tainted every relationship i’ve had since the
      · roller-coaster success of my first book.”
      · i've had sexual partners, but never a girlfriend.
  Novel sentences:
    · [BOOK_002, CELL_A, tertile=end, p=0.70]
        Can I assume you two don’t have a…relationship?”
    · [BOOK_001, CELL_C, tertile=end, p=0.52]
        You will say anything to save your lover.
    · [BOOK_002, CELL_A, tertile=middle, p=0.64]
        But I’m not avoiding a good relationship.
  Pass A/B/C:
    A lexical: ARC_4
        Main keywords (boyfriend, mate, relationship, partner, status, don, mean) signal
        interrogation or anxiety about the relationship itself — not a discrete external
        threat or a repair moment, but ongoing relational distress tied to the couple's
        dynamic. KeyBERT reinforces this: 'emotionally', 'admit', 'worrying', 'ex' point
        to emotional strain and unresolved feelings causing distress within the
    B contextual: ARC_1
        Topic 301 clusters around relationship-status ambiguity and questioning — 'do
        you have a boyfriend/girlfriend?', denials of being in a relationship, and
        challenges about who someone is with. These are predominantly misunderstanding
        or definitional-confusion signals (ARC_1), where characters are unclear or in
        dispute about the nature of their romantic connection. A substantial minority of
    C adjudicate: ARC_1 action=REINTERPRET
        Lexical consensus landed on ARC_4 (relationship-caused distress), but the
        taxonomy placement in 4.3 Secrets, Misunderstandings & Hidden Information — with
        a secondary anchor in 3.3 Ambivalence & Internal Conflict — points to the
        distress being a downstream symptom rather than the primary arc mechanism. The
        contextual dominant ARC_1 (misunderstanding) better captures the generative

============================================================================================
  TOPIC 303 — Confessing Long-Hidden Secrets
============================================================================================
  Taxonomy : 4.3 — Secrets, Misunderstandings & Hidden Information
  Code     : ARC_1  (norm: ARC_1)
  Stage08 snippets:
      · normally, tate would’ve finished the sentence she was working on, but the excitement
      · in mabel’s voice jarred her completely out of the story, derailing her train of
      · i know it might cost me tate, but if i don’t tell him then everything we’ve built
      · will be based on half-truths.” “
      · tate sits down next to me, his eyes grim as he waits for me to share all the things
      · that i've been keeping from him for so long.
  Novel sentences:
    · [BOOK_003, CELL_A, tertile=middle, p=0.70]
        Damn it, he wondered if Joshua Tate knew the full extent of what he was taking on.
    · [BOOK_003, CELL_A, tertile=begin, p=0.69]
        Joshua Tate tugged at his collar and cleared his throat, his prominent Adam"s apple
        bobbing as he swallowed audibly. “
    · [BOOK_004, CELL_B, tertile=middle, p=0.45]
        I went to Woodson to interview Chandra Cunningham about Tana Mayfield.
    · [BOOK_005, CELL_B, tertile=middle, p=0.52]
        You seem to have the exclusive attention of the Lady Mayfield,” Kent mentioned once
        greetings had been exchanged between the three. “
  Pass A/B/C:
    A lexical: ARC_10
        Main rep offers a cluster of character names (tate, logan, kenzie, ang, chace,
        kent, sophia) with no relational-arc signal beyond 'agreed'; KeyBERT yields
        procedural/observational terms (nods, sentence, speaking, planned, anticipation,
        muffled, worrying, judging, winked) that suggest scene-level narration without a
        clear arc function; POS rep mixes physical/situational nouns and adjectives
    B contextual: ARC_0
        Topic 303 clusters around proper names — Joshua Tate (BOOK_003),
        Tana/Dotty/Laurel Mayfield (BOOK_004/005), and Tyrese Moore (BOOK_007). None of
        these sentences depict a romantic main-couple dynamic; they reference supporting
        characters, investigative dialogue, and third-party interactions. BOOK_005_5
        hints at external plot manipulation (a staged accident, time travel), but the
    C adjudicate: ARC_1 action=REINTERPRET
        Adjudication resolves the tension between lexical consensus (ARC_10 unclear) and
        contextual dominant (ARC_0 off_target) by applying taxonomy metadata. Taxonomy
        4.3 (Secrets, Misunderstandings & Hidden Information) is a strong signal that
        the topic content centers on hidden information or misunderstanding dynamics
        between the main couple — a classic REFINED_FALLING beat. ARC_0 (off_target) is

============================================================================================
  TOPIC 305 — Confessing A Lifelong Regret
============================================================================================
  Taxonomy : 4.5 — Reconciliation, Commitments & HEA
  Code     : ARC_7  (norm: ARC_7)
  Stage08 snippets:
      · i know that now, and i’ll go to my grave regretting what i did to you.” “
      · come on in, you’ll no doubt regret it.
      · you’ll regret that.’ ‘
  Novel sentences:
    · [BOOK_001, CELL_B, tertile=middle, p=0.66]
        You are surely not intending to imply that you are beginning to regret this marriage
        already?’ ‘
    · [BOOK_001, CELL_B, tertile=end, p=0.53]
        I fear that my careless remarks must have been the cause of that outburst.
  Pass A/B/C:
    A lexical: ARC_4
        Across all four keyword lists, the dominant signals are regret (regret,
        regretted, regrets, regretting, regrettable), emotional distress (fears, upset,
        embarrassing), and relational missteps (fumbled, handled, acted, remark,
        decision). The presence of 'promise' and 'assure' suggests the relationship is
        implicated — a promise or commitment has been broken or mishandled, generating
    B contextual: ARC_10
    C adjudicate: ARC_7 action=REINTERPRET
        The lexical consensus (ARC_4) and contextual dominant (ARC_10) diverge, but the
        convergent weight of the supporting metadata resolves the ambiguity toward
        ARC_7. Radway R10 ('heroine reinterprets hero's behaviour as result of previous
        hurt') is a canonical trust-restoration mechanism: the heroine's cognitive
        reframing of the hero's past actions is precisely what ARC_7 requires —
    !! manual_review_required

============================================================================================
  TOPIC 314 — Fiancé Becoming A Stranger
============================================================================================
  Taxonomy : 4.3 — Secrets, Misunderstandings & Hidden Information
  Code     : ARC_10  (norm: ARC_10)
  Stage08 snippets:
      · macie had spent far more time praying for blake and far less time being driven by
      · her constantly-shifting emotions.
      · she peeked out and verified that it was indeed blake, then promptly shut the door in
      · his face to remove the chain. “
      · the blake i am engaged to is slowly disappearing in my mind, and being replaced by a
      · complete and utter stranger.
  Novel sentences:
    · [BOOK_001, CELL_A, tertile=middle, p=0.49]
        I wondered about that when you first told me you’d be staying with Brant.
  Pass A/B/C:
    A lexical: ARC_10
        Main rep is dominated by character names (blake, dion, macie, breydan, hewitt)
        and social/group terms (mates, grog, evite, addressing, motioned) with no clear
        arc signal. KeyBERT adds 'engaged', 'attracted', 'overheard', 'emotions',
        'causing' — suggestive of some interpersonal dynamic but not pinpointing a
        specific arc stage (no clear conflict, repair, disclosure, or commitment cue).
    B contextual: ARC_10
        Topic 314 appears to be a character-name topic — sentences are almost entirely
        name invocations or very short address fragments (Brant, Blake, Phoenix) with no
        surrounding narrative context that reveals a relationship dynamic, conflict,
        repair, or arc event. The sentences are drawn from multiple books with different
        named characters, confirming this is a BERTopic cluster anchored on proper-name
    C adjudicate: ARC_10 action=KEEP
        Both lexical consensus and contextual dominant converge on ARC_10
        (unclear_arc_role), indicating the topic does not resolve cleanly into a single
        narrative-arc function. The taxonomy metadata (4.3 Secrets, Misunderstandings &
        Hidden Information; secondary 3.3 Ambivalence & Internal Conflict) suggests
        content that could plausibly map to ARC_1 (misunderstanding) or ARC_5
    !! manual_review_required

============================================================================================
  TOPIC 362 — Keeping Someone Watched and Close
============================================================================================
  Taxonomy : 4.3 — Secrets, Misunderstandings & Hidden Information
  Code     : ARC_10  (norm: ARC_10)
  Stage08 snippets:
      · come on, i’ll get you a drink,’ rory said. ‘
      · they’ll expect me to keep her close, to make sure she doesn’t discover what we are,”
      · rory answered.
      · and goddess willing i’ll be ready for it, thought rory as she ignored his comment to
      · follow amber out to the sitting room.
  Novel sentences:
    · [BOOK_001, CELL_B, tertile=begin, p=0.49]
        For we have seen how far Kelsey is willing to go for what he wants.”
    · [BOOK_001, CELL_B, tertile=begin, p=0.47]
        He would go slowly, wisely, even though he was more resolved than ever to see Kelsey
        repaid for his ills against others.
    · [BOOK_001, CELL_B, tertile=begin, p=0.46]
        Yet he’d had no time to grieve their loss, for he had immediately become embroiled
        in this conflict with the Earl of Kelsey.
  Pass A/B/C:
    A lexical: ARC_10
        Main keywords are dominated by proper nouns (rory, yamane, kingman, darlington,
        ayida, damballah) and a survival cue ('survived'), offering no clear relational
        arc signal between a main couple. KeyBERT yields procedural/social interaction
        words (answering, willing, sir, expect, pretending, embarrassed, introduce,
        issue, wondering) that suggest a scene of social navigation or awkward
    B contextual: ARC_10
        Topic 362 clusters around the name 'Kelsey' across two very different books. In
        BOOK_001, Kelsey is an antagonist (Earl of Kelsey) and all sentences describe
        external conflict/rivalry with no main-couple involvement — coded ARC_9. In
        BOOK_002, Kelsey appears to be a character whose identity relative to the main
        couple is unclear from fragments alone; 'Kelsey's heart sank' suggests emotional
    C adjudicate: ARC_10 action=KEEP
        Both lexical consensus and contextual dominant converge on ARC_10
        (unclear_arc_role). The taxonomy tag 4.3 (Secrets, Misunderstandings & Hidden
        Information) suggests the topic could plausibly map to ARC_1 (misunderstanding)
        or ARC_5 (disclosure), but neither signal is strong enough to override the
        double ARC_10 signal from Passes A and B without additional textual evidence.
    !! manual_review_required

============================================================================================
  TOPIC 319 — Confessing A Costly Mistake
============================================================================================
  Taxonomy : 4.3 — Secrets, Misunderstandings & Hidden Information
  Code     : ARC_1  (norm: ARC_1)
  Stage08 snippets:
      · but you have a way of letting me know when you think i’ve made the wrong one.” “
      · i’ve made many mistakes and maybe i should have come back a year ago.
      · it was a mistake for which i’ve paid dearly.” “
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=middle, p=0.42]
        They’re fundamental y flawed, I can’t—” “ ‘Flawed’ being the key word,” Josh points
        out.
  Pass A/B/C:
    A lexical: ARC_1
        Main keywords ('mistake', 'mistakes', 'flaw', 'error', 'errors', 'biggest',
        'terrible', 'made') strongly signal a misunderstanding or misjudgment frame —
        the vocabulary of recognizing a wrong belief or wrong action that drove a rift,
        which is the lexical signature of ARC_1 (misunderstanding). KeyBERT ('occurred',
        'thinks') and POS ('latest', 'bigger') are too sparse and neutral to anchor any
    B contextual: ARC_1
        Topic 319 clusters around language of mistakes, wrongness, accidents, and being
        flawed — all hallmarks of misunderstanding or misjudgment rather than escalating
        conflict or external plot. The majority of sentences (12/20) express that
        something was wrong, mistaken, or accidental, fitting ARC_1 (misunderstanding).
        A minority show interpersonal friction/disagreement (ARC_2) or
    C adjudicate: ARC_1 action=KEEP
        Both lexical consensus and contextual dominant converge on ARC_1
        (misunderstanding). Taxonomy 4.3 (Secrets, Misunderstandings & Hidden
        Information) directly corroborates this classification, with 3.2 (Negative
        Emotions & Distress) as a secondary signal consistent with the emotional fallout
        of a misunderstanding rather than an independent arc role. The topic concerns

============================================================================================
  TOPIC 232 — Conversation Cut Short By Arrival
============================================================================================
  Taxonomy : 4.2 — Ongoing Courtship & Everyday Relational Bonding
  Code     : ARC_10  (norm: ARC_10)
  Stage08 snippets:
      · dex had come in and gabe's conversation with her, the longest conversation that
      · they'd had in the couple of weeks he'd been back, was over.
      · gabe leaned down so he wouldn’t be overheard. “
      · i'll tell you right now falan and gabe are the only people on my team that i'd stake
      · my career— or my balls —on."
  Novel sentences:
    · [BOOK_002, CELL_C, tertile=end, p=0.49]
        Have Remy or the boys been out to question you again or give you more information
        about Joshua’s attack?”
    · [BOOK_003, CELL_A, tertile=end, p=0.70]
        He almost told her to call him Gabe, but he knew his name would sound way too good
        coming from her full lips.
    · [BOOK_003, CELL_A, tertile=end, p=0.69]
        Her name fit her, Gabe had found himself thinking one too many times.
    · [BOOK_003, CELL_A, tertile=begin, p=0.68]
        Gabe pretended to tackle Zach as he pulled the microphone from his hand, but he
        instantly sobered as he turned to Chase and Chloe. “
    · [BOOK_004, CELL_A, tertile=end, p=0.75]
        Her face got red then and she said angrily, "So, Gabe knew and didn't clue me in?
  Pass A/B/C:
    A lexical: ARC_10
        The keyword sets present a tense, emotionally charged conversation between named
        characters (gabe, nick, elwoods) with cues of physical tension (trembling,
        squeezed, cringed, groaned, pained, stroking) and emotional complexity (longing,
        instincts, awareness, distracted, impatiently, overheard). However, the signals
        are mixed: 'longing' and 'stroking' suggest intimacy or desire, while 'cringed,'
    B contextual: ARC_10
        Topic 232 consists entirely of truncated dialogue attribution fragments centered
        on the name 'Gabe' (e.g., 'Gabe said.', 'Gabe murmured.', 'Gabe blinked.').
        These are speech-tag sentence stubs with no recoverable semantic content about
        the romantic relationship or any arc function. The topic appears to be a
        BERTopic artifact capturing a character-name dialogue-attribution pattern rather
    C adjudicate: ARC_10 action=KEEP
        All metadata signals converge on ARC_10. Taxonomy 4.2 (Ongoing Courtship &
        Everyday Relational Bonding) describes routine relational interaction without a
        clear directional arc function. Radway R3 (hero responds ambiguously to heroine)
        is definitionally ambiguous — it neither advances nor retreats the relationship
        in a codeable direction. Radway R7 and R2 as secondary/plausible codes add mild

============================================================================================
  TOPIC 293 — Admitting Jealousy Out Loud
============================================================================================
  Taxonomy : 4.7 — Jealousy & Possessive Romance Conflict
  Code     : ARC_4  (norm: ARC_4)
  Evidence : EXHAUSTIVE packet
  Stage08 snippets:
      · the concept of jealousy is foreign to them.
      · but this jealousy of yours is gonna ruin what you’ve got with j.d.” “i know.” “
      · we’ve been around the markets and —’ as she enthused away, i couldn’t help but feel
      · jealous.
      · should i be jealous of this cayden?”
  Novel sentences:
    · [BOOK_001, CELL_B, tertile=middle, p=0.72]
        I've always maintained that a little bit of jealousy looks good on a man. "
    · [BOOK_001, CELL_B, tertile=end, p=0.71]
        Well, of course I'm jealous," I frowned, poking him in the chest. "
    · [BOOK_001, CELL_B, tertile=end, p=0.63]
        She was also extremely irate over the fact that her boyfriend was using me to make
        her jealous—without my permission, as I've told you a couple of times.
    · [BOOK_001, CELL_B, tertile=end, p=0.62]
        I'm flattered that you're jealous, but you should know by now that no other woman
        could begin to compare with you.
    · [BOOK_001, CELL_B, tertile=end, p=0.61]
        This is not arrogance talking, this is not jealousy, it is simply a matter of
        facts."
    · [BOOK_001, CELL_B, tertile=middle, p=0.55]
        I debated staying where I was, standing firm for ethical reasons, but the thought
        that she'd be in the closed, womb-like confines of the trailer alone with Raphael
        was enough to spike my jealousy count off the chart.
    · [BOOK_001, CELL_B, tertile=begin, p=0.55]
        Not to mention you repeatedly batted your eyelashes at me in an obvious attempt to
        make him jealous.
    · [BOOK_001, CELL_B, tertile=middle, p=0.48]
        I didn't mind a little bit of a possessive attitude, but he was taking things a bit
        too far. "
    · [BOOK_001, CELL_B, tertile=begin, p=0.43]
        I bet you're one of those men who likes to feel superior to women," Roxy said
        suspiciously.
  Pass A/B/C:
    A lexical: ARC_4
        All four keyword lists converge on relationship-caused emotional distress. Main
        keywords ('jealous', 'jealousy', 'jealously', 'irrational', 'twinge', 'pang')
        directly name the internal emotional pain triggered by the romantic
        relationship. KeyBERT adds 'attracted', 'upset', 'emotional', 'concerned',
        'warned', 'assured', pointing to relational anxiety and distress rather than a
    B contextual: ARC_4
    C adjudicate: ARC_4 action=KEEP
        All convergent signals align with ARC_4. Taxonomy 4.7 (Jealousy & Possessive
        Romance Conflict) and secondary 4.4 (Conflict, Distance & Breakup Threats) both
        sit squarely within the falling arc cluster. Radway R2 (heroine reacts
        antagonistically to hero) is a canonical ARC_4 marker — the distress originates
        from within the romantic relationship itself, not from an external threat. R5

============================================================================================
  TOPIC 3 — Demanding An Explanation
============================================================================================
  Taxonomy : 4.4 — Conflict, Distance & Breakup Threats
  Code     : ARC_5  (norm: ARC_5)
  Stage08 snippets:
      · and you have no idea what we’ve seen, what we’ve done— you’ve been in your cosy
      · little world and you just have no—damned— clue! ’
      · sophia, i’ve something to tell you.” “
      · i’ve told them that already.’ ‘
  Novel sentences:
    · [BOOK_002, CELL_B, tertile=middle, p=0.65]
        I’ll tell you whatever you want to know.”
    · [BOOK_002, CELL_B, tertile=middle, p=0.68]
        Well, you know what I mean.” “
    · [BOOK_001, CELL_D, tertile=end, p=0.54]
        No—no, I don’t admit that.’
  Pass A/B/C:
    A lexical: ARC_5
        All four keyword lists converge on disclosure/revelation dynamics. Main keywords
        ('know, tell, don, understand, ask, explain, say, wrong, mean') signal a scene
        structured around communicating or withholding information and seeking
        clarification. KeyBERT keywords ('admit, reveal, realise, assure, speaking') are
        direct disclosure-act verbs — 'admit' and 'reveal' are canonical ARC_5 markers.
    B contextual: ARC_5
        All sentences in this topic cluster around the act of demanding, withholding, or
        offering information — 'Tell me,' 'I demanded to know,' 'I'll tell you whatever
        you want to know,' 'I'm just not supposed to tell you,' etc. This is a strong
        disclosure/revelation pattern (ARC_5). The sentences are highly decontextualized
        fragments with no clear identification of who the speakers are or whether they
    C adjudicate: ARC_5 action=KEEP
        Both lexical consensus and contextual dominant independently converge on ARC_5
        (disclosure). Although the taxonomy tag is 4.4 Conflict, Distance & Breakup
        Threats, disclosure events frequently appear within that zone of the narrative
        arc — a character revealing a secret or truth is a classic falling-arc beat that
        precipitates conflict or distance. The taxonomy label describes the broader

============================================================================================
  TOPIC 194 — Promising to Keep A Secret
============================================================================================
  Taxonomy : 4.3 — Secrets, Misunderstandings & Hidden Information
  Code     : ARC_5  (norm: ARC_5)
  Stage08 snippets:
      · i’ll keep it a secret,” said lucas.
      · i’ll be your dirty little secret,” i joked.
      · i’ll leave that secret for him to reveal.
  Novel sentences:
    · [BOOK_005, CELL_C, tertile=middle, p=0.52]
        Perhaps secret information that he has uncovered, information that would be
        dangerous to the French.’ ‘
    · [BOOK_005, CELL_C, tertile=begin, p=0.38]
        For reasons I cannot disclose I would rather you did not mention the break-in to
        anyone.
  Pass A/B/C:
    A lexical: ARC_5
        All four keyword lists converge on disclosure dynamics. Main is dominated by
        secret/secrets/keep/keeping/kept/reveal/secrecy — the core lexicon of hidden
        information being held or released. KeyBERT reinforces with
        reveal/revealing/hiding/confessed/identity, pointing to an active moment of
        disclosure or near-disclosure. POS adds
    B contextual: ARC_5
        Topic 194 is overwhelmingly about secrets, secrecy, and the act of keeping or
        revealing hidden information — the defining features of ARC_5 (disclosure). The
        vast majority of sentences (17/20) directly reference secrets, secret-keeping,
        or the threat/promise of disclosure. A meaningful subset (BOOK_006 sentences)
        clearly involves the main couple, where one or both partners are concealing
    C adjudicate: ARC_5 action=KEEP
        Both lexical consensus and contextual dominant converge on ARC_5 (disclosure).
        Taxonomy 4.3 (Secrets, Misunderstandings & Hidden Information) directly supports
        a disclosure event — a character reveals or is confronted with concealed
        information, which is the canonical ARC_5 trigger. The secondary taxonomy 9.2
        (Promise, Vow & Future-Tense Speech Acts) suggests a commitment or pledge may

============================================================================================
  TOPIC 242 — Trading Forgiveness For Old Wrongs
============================================================================================
  Taxonomy : 4.5 — Reconciliation, Commitments & HEA
  Code     : ARC_6  (norm: ARC_6)
  Stage08 snippets:
      · not if you’ll forgive him.” “
      · he’ll never forgive you.
      · okay, how’s this — i’ll forgive you for summer if you forgive me for kabir.” “
  Novel sentences:
    · [BOOK_003, CELL_B, tertile=begin, p=0.55]
        Any man delivering such a speech to the lady he had planned to marry—a lady who had
        waited faithfully for him—should have had the grace to appear remorseful, or at
        least apologetic.
  Pass A/B/C:
    A lexical: ARC_6
        All four keyword lists converge on apology and forgiveness as the dominant
        signals. Main contains 'forgive,' 'forgiveness,' 'forgiven,' 'forgiving,' and
        the pleading 'please, can, hope' — classic repair-seeking language. KeyBERT
        reinforces this with 'apology,' 'fault,' 'willing,' and 'harshly/terribly/hurts'
        (acknowledging harm done). POS adds 'apology,' 'treatment,' 'actions,' and
    B contextual: ARC_6
    C adjudicate: ARC_6 action=KEEP
        All converging signals point to ARC_6. The lexical and contextual consensus is
        reconciliation/repair. Taxonomy 4.5 (Reconciliation, Commitments & HEA) with
        secondary 4.3 (Secrets/Misunderstandings) is fully consistent: the couple is
        moving through the repair of a misunderstanding or prior hurt toward restored
        closeness. Radway R10 (heroine reinterprets hero's behaviour as result of

============================================================================================
  TOPIC 85 — Offering and Refusing An Apology
============================================================================================
  Taxonomy : 4.4 — Conflict, Distance & Breakup Threats
  Code     : ARC_6  (norm: ARC_6)
  Stage08 snippets:
      · he said he wanted to apologize.
      · i need to apologize to you, ruby.
      · oh, i'm so not gonna apologize for that."
  Novel sentences:
    · [BOOK_001, CELL_D, tertile=end, p=0.54]
        He tried to get back in my good graces with a box of chocolates a couple of days
        later, but he never did apologize.” “
    · [BOOK_001, CELL_D, tertile=begin, p=0.54]
        And you made it quite clear that you thought I was overreacting to the situation.”
    · [BOOK_001, CELL_D, tertile=end, p=0.53]
        Between Cornelia, Emily Taylor and Helen Washburn, I’ve been apologized to every day
        this week.”
  Pass A/B/C:
    A lexical: ARC_6
        All four keyword lists converge on repair behavior between the main couple. Main
        is saturated with apology-act vocabulary ('sorry', 'apologize', 'apology',
        'apologizing', 'apologized', 'owe', 'apologise'), which is the canonical lexical
        signature of ARC_6 (repair). KeyBERT reinforces this with 'apology',
        'apologize', 'forgive', 'fault', and 'embarrassed', indicating acknowledgment of
    B contextual: ARC_6
        Topic 85 is overwhelmingly characterized by apology and sorry expressions ('I'm
        sorry', 'I am sorry', 'Did you just apologize?', 'No harm was done'). These are
        canonical repair gestures following conflict, mapping clearly to ARC_6 (repair).
        One sentence (BOOK_001_4) references a prior accusation of overreacting,
        suggesting a misunderstanding context (ARC_1), and two 'Excuse me?' fragments
    C adjudicate: ARC_6 action=KEEP
        Both lexical consensus and contextual dominant converge on ARC_6 (repair). The
        primary taxonomy tag 4.4 (Conflict, Distance & Breakup Threats) might suggest a
        falling-arc code such as ARC_2 or ARC_3, but the secondary tag 4.5
        (Reconciliation, Commitments & HEA) and the consistent Pass A/B signal indicate
        the topic captures the turn toward repair rather than the conflict itself. ARC_6

============================================================================================
  TOPIC 126 — Fingertips Stroking Her Cheek
============================================================================================
  Taxonomy : 2.2 — Kissing & Non-Explicit Affection
  Code     : ARC_7  (norm: ARC_7)
  Stage08 snippets:
      · she lifted her chin. “
      · he lifted a hand and stroked a finger down her cheek. ‘
      · she lifted her hand and caressed his cheek. "
  Novel sentences:
    · [BOOK_001, CELL_B, tertile=begin, p=0.82]
        He reached out now, stroked his fingers down her cheek to tip her face to his.
    · [BOOK_001, CELL_B, tertile=end, p=0.80]
        He caught her back to him, spreading his fingers over her uninjured cheek. “
    · [BOOK_002, CELL_A, tertile=middle, p=0.81]
        His long fingers cradled her cheeks as he gave her a questioning stare. “
    · [BOOK_002, CELL_A, tertile=middle, p=0.79]
        His face lowered over hers, and his fingertips settled on her jaw, gently adjusting
        the angle of her head.
    · [BOOK_002, CELL_A, tertile=middle, p=0.79]
        His fingers slid over the hot surface of her cheek, and he gently pressed her head
        to his shoulder. “
    · [BOOK_002, CELL_A, tertile=middle, p=0.79]
        He bent his head, nuzzling his jaw against the pale silk of her palm. “
    · [BOOK_002, CELL_A, tertile=end, p=0.79]
        His mouth touched her burning forehead and followed the wing of her brow. “
  Pass A/B/C:
    A lexical: ARC_7
        Main, KeyBERT, and MMR are dominated by intimate tactile gestures directed at
        the face and body (cheek, chin, lifted, cupped, stroked, caressed, thumb,
        touched, cradled, swiped) that collectively signal tender physical closeness
        consistent with trust being restored or reinforced between the couple —
        qualifying as ARC_7 (restored trust/reassurance). POS introduces 'annoyance' and
    B contextual: ARC_7
    C adjudicate: ARC_7 action=KEEP
        All converging signals align on ARC_7. Taxonomy 2.2 (Kissing & Non-Explicit
        Affection) and 1.7 (Facial Expression & Non-Verbal Cues) describe the
        physical/expressive register through which trust and closeness are being
        restored — not merely expressed for the first time. Radway R8 (hero treats
        heroine tenderly) and R9 together indicate a relational repair or deepening

============================================================================================
  TOPIC 167 — Planning A Wedding Reception
============================================================================================
  Taxonomy : 5.3a — Romantic Social Rituals & Public Couple Recognition
  Code     : ARC_8  (norm: ARC_8)
  Evidence : EXHAUSTIVE packet
  Stage08 snippets:
      · it’s my dream job, but instead of shooting brides, i’ll be shooting naked women.
      · we'll get married next summer in the church in maine that my mother would take me to
      · every sunday.
      · the ‘ceremony’ in boorowa might just be signing a few papers, but carley’s planned a
      · wedding reception they’ll never forget.” “
      · on the eve of your wedding.”
  Novel sentences:
    · [BOOK_001, CELL_A, tertile=middle, p=0.72]

Later: REFINED_FALLING / REFINED_RISING deltas and RARC; EXTERNAL_PLOT_CONFLICT kept
outside the arc equation.

print("H6 audit review complete.")